### ISSUE TITLE
Bash script unclear about why it can't find `codecov.yml` when source-control not present

### ISSUE THREAD

**Issue by adamdicarlo** [codecov/codecov-bash#100]
Feature request for codecov bash script:

1. Allow _at least_ project-root-only `codecov.yml` files when source control is unavailable
2. Show _why_ `codecov.yml` was not found when it's not (eg. "We couldn't find .git or .hg directories, so we only looked in the project-root directory")

Figuring out _why_ codecov.yml wasn't being found sucked up a few hours of my and my coworker's time.

Our builds are in CodeShip Pro; since it's a Docker build, the `.git` directory is unavailable. Codecov's bash script says `Yaml not found!` despite it being present in the current directory (the problem was actually that `.git` is unavailable).

Here's the code in the bash script that is causing this problem for us:

```
yaml=$(cd "$git_root" && \
       git ls-files "*codecov.yml" "*codecov.yaml" 2>/dev/null \
       || hg locate "*codecov.yml" "*codecov.yaml" 2>/dev/null \
       || echo '')
yaml=$(echo "$yaml" | head -1)
```

Related: https://github.com/codecov/codecov-bash/issues/84

**Comment by stevepeak** [comment]
> I'm sorry to hear there was an issue related to finding the yaml. I apologize for the inconvenience this caused. 😦 

I think your feedback is very helpful. I'll add your suggestions now.

**Comment by stevepeak** [comment]
@adamdicarlo Thoughts on 63c7f29

**Comment by will-weston** [comment]
This still seems like a problem, followed instructions here:
https://docs.codecov.io/docs/testing-with-docker
but the bash script was unable to locate the `codecov.yml` located in `pwd`
Current directory structure in the container:
```
-> docker run -it testing:latest ls
Testing.sln  NuGet.config  codecov.yml  src  tests
```
Current script not finding the yaml file
```
docker run -it testing:latest "bash <(curl -s https://codecov.io/bash)"
...
Yaml not found, that's ok! Learn more at http://docs.codecov.io/docs/codecov-yaml
...
```
I'm currently using this work around. 
```
docker run -it testing:latest "bash <(curl -s https://codecov.io/bash) -y ./codecov.yml"
...
Yaml found at: ./codecov.yml
...
```

**Comment by hparadiz** [comment]
Running into this problem as well. Our deployment strips .git entirely because the repo with history is huge but what we want to deploy is a small subset of that huge payload so we just send over the one version we want to actually deploy.

**Comment by ruffsl** [comment]
FYI , it looks like the `-y` arg has since been deprecated:

https://community.codecov.io/t/option-y-in-bash-script-not-working-as-intended/1279/5

Looks like the search logic has been updated though:

https://github.com/codecov/codecov-bash/blob/9d9a1b61c04e8aea9ebb8c200d1fbc399eb6cc99/codecov#L963-L968
