### ISSUE TITLE
Error when running codecov -f $resolvedResultFile -X gcov

### ISSUE THREAD

**Issue by johlju** [codecov/codecov-bash#108]
We have started seeing an error a couple of weeks back when running the following (in AppVeyor using PowerShell script). It seems this is an error that get reported in the Python code for codecov. 
Was hoping for some insight what could be going on. 

I more detailed write up can be seen in the issue https://github.com/PowerShell/DscResource.Tests/issues/203.

```
$null = pip install git+git://github.com/codecov/codecov-python.git
uploadResults = codecov -f $resolvedResultFile -X gcov
```

```
codecov : The filename, directory name, or volume label syntax is incorrect.
At C:\projects\xnetworking\DscResource.Tests\DscResource.CodeCoverage\CodeCovIo.psm1:336 char:22
+     $uploadResults = codecov -f $resolvedResultFile -X gcov
+                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (The filename, d...x is incorrect.:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
```
See test run here: https://ci.appveyor.com/project/PowerShell/xnetworking/build/3.1.786.0#L4671

**Comment by johlju** [comment]
My bad. Wrong repo 😞

**Comment by ramlongcat** [comment]
i have the same issue and my repo is correct.
im using AppVeyor and a build that used to work in December is now failing with that exact error message.
FYI in my experience the error started to appear around December 15th (and maybe it can help but im using tags; the API documentation about flag badges is still incomplete BTW)

**Comment by stevepeak** [comment]
@ramlongcat can you share you stdout error? Is it the same?

We do have a codecov.exe that may be a better option: https://github.com/codecov/codecov-exe

**Comment by ramlongcat** [comment]
sure:
```
codecov : The filename, directory name, or volume label syntax is incorrect.
At line:5 char:3
+   codecov -f (Resolve-Path "server-coverage.xml") -t ${env:CODECOV_UP ...
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (The filename, d...x is incorrect.:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
```

**Comment by ramlongcat** [comment]
BTW it seems the issue has moved [here ](https://github.com/PowerShell/DscResource.Tests/issues/203)for some reason.
