### ISSUE TITLE
can't find the report for python when jenkins workspace is using symbol link

### ISSUE THREAD

**Issue by swimablefish** [codecov/codecov-bash#112]
Hi,  we're using symbol link in our jenkins:  /var/lib/jenkins  -->  /mnt/jenkins.
For python,  we found the script can't detect the coverage report.
The reason is the environment vars which are passed by jenkins,   **PWD** is different from **WORKSPACE**.
PWD=/mnt/jenkins/workspace/jobname
WORKSPACE=/var/lib/jenkins/workspace/jobname
If we force to change PWD to /var/lib/jenkins/workspace/jobname, the script can detect the report. 
Otherwise, it can't.

**Comment by stevepeak** [comment]
Interesting. We do not use the variable `WORKSPACE` in our upload script. I'm not sure how that value would change how Codecov bash is executed.

We could apply a patch that could check the `PWD` and `WORKSPACE` during the script. But is this issue specific to your CI? I have not heard this issue before.

**Comment by swimablefish** [comment]
We use jenkins pipeline, so it should be PWD's problem. 
If PWD is set to /mnt/jenkins/workspace/jobname, the codecov can't find the report. And it will show error status for the commit in codecov.io's commit dashboard.
And we add branch protection with codecov-project, so the pull request's status will always be pending.

**Comment by stevepeak** [comment]
Did you find a workaround? I'm not quite sure how to resolve this issue.

**Comment by swimablefish** [comment]
I didn't modify the script. I just reset the PWD=WORKSPACE, then it worked.

**Comment by stevepeak** [comment]
Ok. I'll add this to our caveats and hope it helps others that may be having the same issue.
