### ISSUE TITLE
CircleCI 2.0 codecov-bash generates nothing but codecov-python works

### ISSUE THREAD

**Issue by mloskot** [codecov/codecov-bash#118]
This is continuation of an issue investigation I described in details as comment for https://github.com/codecov/codecov-bash/issues/113#issuecomment-381750243
Since I suspect this might be a separate problem, I decided to open new new issue and copy my comment here.

UPDATE: See at the bottom for fix/workaround solution.

-----

I'm also hitting very similar problem as #113 trying to generate coverage reports from CircleCI 2.0 builds of Boost.Geometry library.

## Configuration overview

- Config files in https://github.com/mloskot/geometry/tree/develop
- Build https://circleci.com/gh/mloskot/geometry/273 (Note, this is one of recent builds that runs tests, generates and submits coverage)
- Codecov report expected at https://codecov.io/gh/mloskot/geometry

In `Jamfile` makefile for the project I added custom build variant named `coverage`:

```
variant coverage
  : debug
  : <cxxflags>"--coverage"
    <linkflags>"--coverage"
  ;
```

so the compilation and linking command lines seems fine:

```
"g++" -fPIC -m64 -O0 -fno-inline -Wall -g --coverage -std=c++11 
  -DBOOST_ALL_NO_LIB=1 -DBOOST_NO_AUTO_PTR  -I"../.." -I"../../boost/geometry/extensions/contrib/ttmath" -I"test"
    -c -o "../../bin.v2/libs/geometry/test/core/core_access.test/gcc-7.3.0/coverage/access.o" "test/core/access.cpp"

"g++" -o "../../bin.v2/libs/geometry/test/core/core_access.test/gcc-7.3.0/coverage/core_access"
  -Wl,--start-group "../../bin.v2/libs/geometry/test/core/core_access.test/gcc-7.3.0/coverage/access.o"
    -Wl,-Bstatic  -Wl,-Bdynamic  -Wl,--end-group -fPIC -m64 -g --coverage
```

Then, I basically replicate commands that are successfully used by Boost libraries like https://github.com/boostorg/format or https://github.com/boostorg/date_time on Travis CI.

That is, the invocation of `b2` to build and run tests (for simplicity, single test target `core_access`):

```
echo $BOOST_ROOT
/tmp/project/boost-root
cd $BOOST_ROOT/libs/geometry
$BOOST_ROOT/b2 -d 2 toolset=gcc variant=coverage optimization=off cxxflags="-std=c++11" test/core//core_access
```

and `lcov` and `codecov` commands:

```
cd $BOOST_ROOT
lcov --gcov-tool=gcov --rc lcov_branch_coverage=1 --base-directory "$BOOST_ROOT/libs/geometry" --directory "$BOOST_ROOT" --capture --output-file all.info
lcov --gcov-tool=gcov --rc lcov_branch_coverage=1 --extract all.info "*/boost/geometry/*" --output-file coverage.info
lcov --gcov-tool=gcov --rc lcov_branch_coverage=1 --list coverage.info
bash <(curl -s https://codecov.io/bash) -X gcov -x /usr/local/bin/gcov
```

I also use similar fixes in `codecov.yml`:

```
fixes:
  - */boost-root/boost/::include/boost/
```

because for modular Boost, super-project paths need to be mapped to paths inside the `boostorg/geometry` repository:

```
/tmp/project/boost-root/boost/geometry => include/boost/geometry
```

## Problem: .codecov.yml (solved)

First, I hit the `GitHub HTTP 404` about missing `.codecov.yml` which was present in the root of the repo.
I fixed that by renaming the file to `codecov.yml` (leading dot removed) and now the file is found.

## Problem: git (solved)

On CircleCI, I'm using the official gcc:7.3 docker image where all the commands are in place:

```
$ git --version
git version 2.11.0
$ which gcov
/usr/local/bin/gcov
$ gcov --version
gcov (GCC) 7.3.0
$ which lcov
/usr/bin/lcov
$ lcov --version
lcov: LCOV version 1.13
```

## Comment: testing-with-docker

UPDATE: I'm convinced this solution does not apply to Docker use on CircleCI

Might be, I misunderstand this "another technique", but in my opinion it does not apply to Circle CI 2.0.
Circle CI makes use of docker completely transparent.
There is no direct invocation of docker as it is required on Travis CI.

## Problem: WARNING No files found in report

All my coverage submissions end up with basically the very same WARNING.
Here is a recent one https://codecov.io/gh/mloskot/geometry/commit/535cc9136a99d9c87e03384bb67f0a2e335dfa12

```
Apr 16 22:46:25 [INFO] INFO GitHub HTTP 200 {"bot": "mloskot", "commit": "535cc91", "endpoint": "/repos/mloskot/geometry/contents/codecov.yml", "event": "api", "method": "GET", "public": "t", "rlr": "1523911636", "rlx": "4783", "rly": "5000", "service": "github", "slug": "mloskot/geometry", "task": "upload"}
Apr 16 22:46:25 [INFO] INFO Yaml found in service. {"bot": "mloskot", "commit": "535cc91", "public": "t", "service": "github", "slug": "mloskot/geometry", "task": "upload"}
Apr 16 22:46:26 [INFO] INFO GitHub HTTP 200 {"bot": "mloskot", "commit": "535cc91", "endpoint": "/repos/mloskot/geometry/commits/535cc9136a99d9c87e03384bb67f0a2e335dfa12", "event": "api", "method": "GET", "public": "t", "rlr": "1523911636", "rlx": "4782", "rly": "5000", "service": "github", "slug": "mloskot/geometry", "task": "upload"}
Apr 16 22:46:26 [INFO] INFO GitHub HTTP 200 {"bot": "mloskot", "commit": "535cc91", "endpoint": "/search/issues", "event": "api", "method": "GET", "public": "t", "rlr": "1523911646", "rlx": "29", "rly": "30", "service": "github", "slug": "mloskot/geometry", "task": "upload"}
Apr 16 22:46:27 [INFO] INFO Retrieved report for processing. {"bot": "mloskot", "commit": "535cc91", "public": "t", "service": "github", "slug": "mloskot/geometry", "task": "upload", "url": "v4/raw/2018-04-16/9817881E9BBE4DAB15C45C5A595728C4/535cc9136a99d9c87e03384bb67f0a2e335dfa12/74cc71e5-2f87-42a7-83c2-82db6710f10b.txt"}
Apr 16 22:46:27 [INFO] INFO Yaml exists at current location. {"bot": "mloskot", "commit": "535cc91", "public": "t", "service": "github", "slug": "mloskot/geometry", "task": "upload"}
Apr 16 22:46:32 [WARNING] WARNING No files found in report. {"bot": "mloskot", "commit": "535cc91", "public": "t", "service": "github", "slug": "mloskot/geometry", "task": "upload"}
```

I'm running out of ideas (and Web searching fu) on how to solve the problem.

I'd be greatful if someone could help to diagnose where is the problem and how to fix it.

-----

## UPDATE with FIX

Instead of codecov-bash, switch to codecov-python and the beautiful Codecov reports are now generated :-)

Instead of running
- `bash <(curl -s https://codecov.io/bash) -X gcov`

now I run this
- `pip install --user https://github.com/codecov/codecov-python/archive/master.zip`
- `~/.local/bin/codecov -X gcov -f`

It seems the bash uploader is having a problem here.

The only problem I noticed is browsing to the files in the report because the report seems to include absolute paths reflecting structure in my CircleCI: - `/tmp/project/boost-root/boost/geometry`

I guess, that I need to fix by refining my `fixes`:

```
fixes:
  - */boost-root/boost/::include/boost/
```

**Comment by drazisil** [comment]
Closing stale issues, not aware of this still happening.
