### ISSUE TITLE
Cut down output verbosity

### ISSUE THREAD

**Issue by pitrou** [codecov/codecov-bash#121]
When I try out codecov on our repo, I get 2000+ lines of output:
https://travis-ci.org/pitrou/arrow/builds/376803020#L1988

Typically, I'm not interested in seeing information about every covered file on stdout. It would be nice to have a flag to have a much less verbose output without giving up entirely on important status or errors messages (such as upload outcome and results URL).

**Comment by stevepeak** [comment]
@pitrou may I ask that you try this out.

```
bash <(curl -s https://raw.githubusercontent.com/codecov/codecov-bash/4678d212cce2078bbaaf5027af0c0dafaad6a095/codecov) -X gcovout
```
Let me know if that does the trick :)

**Comment by pitrou** [comment]
It worked!
* C++ step: https://travis-ci.org/pitrou/arrow/jobs/377629235#L5595
* Rust step: https://travis-ci.org/pitrou/arrow/jobs/377629243#L1650

**Comment by pitrou** [comment]
Hi @stevepeak, will this change be in the official upload script soon?

**Comment by drazisil** [comment]
Closing stale issue, I'm not aware of this still being an problem.
