### ISSUE TITLE
find of gcov fails due to PATH on AppVeyor

### ISSUE THREAD

**Issue by joachimmetz** [codecov/codecov-bash#126]
When trying to run [codecov](https://github.com/codecov/codecov-bash/blob/master/codecov) on AppVeyor it yields the following error when trying to find gcov files

```
find: The current directory is included in the PATH environment variable, which is insecure in combination with the -execdir action of find.  Please remove the current directory from your $PATH (that is, remove "." or leading or trailing colons)
```

(likely) The relevant find: https://github.com/codecov/codecov-bash/blob/master/codecov#L955

**Comment by joachimmetz** [comment]
It seem to have changed in https://github.com/codecov/codecov-bash/commit/1ac948214de2ebf4b9a5a764bf428f932457f296

**Comment by ellio167** [comment]
Agreed, https://github.com/codecov/codecov-bash/commit/1ac948214de2ebf4b9a5a764bf428f932457f296, is causing a problem for https://github.com/openkim/kim-api/commit/cc5c14a41636b7a30006f5915b435d677e294f59 too.

**Comment by thomasrockhu** [comment]
I believe this has been fixed via https://github.com/codecov/codecov-bash/pull/249, but if not, we do not use `-execdir` [anymore](https://github.com/codecov/codecov-bash/pull/249)
