### ISSUE TITLE
Is buildkite officially supported?

### ISSUE THREAD

**Issue by joshma** [codecov/codecov-bash#129]
It looks like https://github.com/codecov/codecov-bash/commit/df2c95fee48d30cfeeae4354a0bf9da0950d01f9 added `$BUILDKITE` support, but https://github.com/codecov/codecov-bash#ci-providers doesn't list it.

Should buildkite be added to that list?

**Comment by drazisil** [comment]
Buildkite is now on the supported list in our docs.
