### ISSUE TITLE
Failure while retrieving PHP version from environment on Travis

### ISSUE THREAD

**Issue by garas** [codecov/codecov-bash#133]
Two weeks ago, Codecov started to fail during environment step:

```
==> Appending build variables
    + TRAVIS_OS_NAME
    + TRAVIS_CMD=if
    + [[
/dev/fd/63: eval: line 1219: unexpected EOF while looking for matching `]'
/dev/fd/63: eval: line 1220: syntax error: unexpected end of file
```

Codecov is executed conditionally `if [[ $DEFAULT = 1 && $TRAVIS_PHP_VERSION = 7.0 ]]; then bash <(curl -s https://codecov.io/bash); fi`

I think fault is here:

https://github.com/codecov/codecov-bash/blob/4678d212cce2078bbaaf5027af0c0dafaad6a095/codecov#L489-L493

Maybe stricter regexp `^TRAVIS_.*_VERSION=` would help so it would only match left side of `=`.

**Comment by ryan-williams** [comment]
Hit the same issue while attempting conditional upload based on `TRAVIS_SCALA_VERSION`; [example failure](https://travis-ci.org/lasersonlab/ndarray.scala/jobs/441163668#L996):

```
Appending build variables
    + TRAVIS_OS_NAME
    + TRAVIS_CMD=if
    + [
./codecov: eval: line 1219: unexpected EOF while looking for matching `]'
./codecov: eval: line 1220: syntax error: unexpected end of file
```

fix referenced above worked for me!

**Comment by ADmad** [comment]
I am surprised a critical issue like this hasn't been fixed yet :disappointed:.

**Comment by prijindal** [comment]
Can confirm this issue with travis
In travis.yml
```
if [ "$TRAVIS_DART_VERSION" == "stable" ] && [ $TRAVIS_DART_TEST == true ]; then ./coverage.sh; fi
```

in coverage.sh
```
#!/bin/sh
mkdir coverage
dart --pause-isolates-on-exit --enable_asserts --enable-vm-service test/.test_coverage.dart &
pub run coverage:collect_coverage --uri=http://127.0.0.1:8181 -o coverage/coverage.json --resume-isolates --wait-paused
pub run coverage:format_coverage -l --packages=$(pwd)/.packages -i coverage/coverage.json --report-on=lib -o coverage/lcov.info
curl -s https://codecov.io/bash | bash
```

Output what i am getting
```
==> Detecting git/mercurial file structure
==> Appending build variables
    + TRAVIS_OS_NAME
    + TRAVIS_CMD=if
    + [
bash: eval: line 1219: unexpected EOF while looking for matching `]'
bash: eval: line 1220: syntax error: unexpected end of file
```

**Comment by prijindal** [comment]
jobovy/galpy@01f0256 seems to work even for me.
I simply replaced ```curl -s https://codecov.io/bash | bash``` with
````
curl -s https://codecov.io/bash > coverage/.codecov
sed -i -e 's/TRAVIS_.*_VERSION/^TRAVIS_.*_VERSION=/' coverage/.codecov
chmod +x coverage/.codecov
./coverage/.codecov

**Comment by ADmad** [comment]
@stevepeak Are you no longer interested in maintaining this repo/project ?

**Comment by blueyed** [comment]
Using `env -u TRAVIS_CMD …` (for Python) also works around it.

I was using `-n $TRAVIS_PYTHON_VERSION` to use it for the name.

But clearly this `printenv | grep` should be fixed..

**Comment by tvdijen** [comment]
I hate doing this, but... BUMP!
