### ISSUE TITLE
codecov fails in CircleCI on merge commits

### ISSUE THREAD

**Issue by eps1lon** [codecov/codecov-bash#134]
When running `bash <(curl -s https://codecov.io/bash)` on a PR in CircleCI that has a merge commit as the latest commit codecov will fail with 
```bash
HTTP 400
Commit sha does not match Circle build.
```

[Full report](https://circleci.com/gh/mui-org/material-ui/46206?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link)

I guess this fixable on our end if we call it with `-C $CIRCLE_SHA1` or simply add empty commits after merges but I'd like to understand the reason for that behavior.

**Comment by alejandrovelez7** [comment]
Was this fixed? I see some messages along the lines of: `Fixing merge commit SHA` when using the bash uploader. But we still see unexpected results when codecov runs on a PR with a merge commit as it's latest commit.

**Comment by evantorrie** [comment]
Still not fixed. Is this just a CircleCI issue?

**Comment by thomasrockhu** [comment]
@evantorrie would you be able to supply a circleci build URL?

**Comment by evantorrie** [comment]
@thomasrockhu Here's an [example](https://app.circleci.com/pipelines/github/open-telemetry/opentelemetry-go/3282/workflows/91d7f1e0-0449-4c98-871a-47c2d90a76c3/jobs/4748). Check the `Upload Coverage Results` step.

The corresponding commit was a "merge" from master into the PR.  Here's a [link to the PR](https://github.com/open-telemetry/opentelemetry-go/pull/1108).

**Comment by thomasrockhu** [comment]
Thanks @evantorrie, this is going to take a bit of time to investigate properly to handle all use cases. For now, the workaround is to specify `-C $CIRCLE_SHA1`. I'll update here as we work through the issue.

**Comment by evantorrie** [comment]
Thanks @thomasrockhu. Regarding using `-C $CIRCLE_SHA1`, it's unclear to me how to do this using the [Codecov CircleCI Orb](https://github.com/codecov/codecov-circleci-orb), since it seems to require passing an extra parameter which is not supported in the existing Orb code.

I opened https://github.com/codecov/codecov-circleci-orb/pull/48 to address this, but it doesn't appear that a reviewer has looked at that yet.

**Comment by thomasrockhu** [comment]
@eps1lon, @alejandrovelez7, @evantorrie, we recently made some changes to the bash uploader here. Would you mind taking a look to see if this is still an issue?

**Comment by eps1lon** [comment]
We're using `-C $CIRCLE_SHA1` now. I don't plan on testing if this is no longer necessary since `-C` has been working for us.

**Comment by alejandrovelez7** [comment]
@thomasrockhu We've transitioned to Buildkite since then so can't help out sadly! We got around this at the time by squashing our PRs too if that helps.
