### ISSUE TITLE
Make script installable

### ISSUE THREAD

**Issue by tabuchid** [codecov/codecov-bash#14]
Because of security concerns I'd like to install this bash uploader instead of piping the output of a network call through bash. This leaves a couple of options with the current setup. 
1. I can just download the script and include it in my project.
  The downside on this is I love versioning, if there are updates to the script I have to include them into my project manually.
2. Include this repo as a git submodule in my project. This is a decent solution but does add some complexity to my project as well as some bloat. Its probably what I'll do until there is a better solution.

Are there any plans to add this to homebrew, apt, or other dependency managers?

**Comment by stevepeak** [comment]
I have not thought about adding it to other dependency managers, its a fine idea.

I'll be working on the Python uploader to do the same tasks as the bash for those that prefer that method.

**Comment by tabuchid** [comment]
Using the Python uploaded would work so long as it finds all the same kinds
of coverage files. Bonus cause it's installable via pip right?

**Comment by stevepeak** [comment]
Correct! I'll be working on this soon. For now, you can use the Bash uploader if you'd like. If security is a concern then please download [this version](https://raw.githubusercontent.com/codecov/codecov-bash/cd5c049f565f0d9a5d4114d1928881e62378ca63/codecov) until the Python project has caught up with the Bash uploader.

Thank you!

**Comment by stevepeak** [comment]
@tabuchid our Node and Python uploaders operate in the same way as the bash. All three of these will be maintained for future growth of Codecov and its features. 

Do you have a suggestion to improve the bash uploader?

**Comment by jayvdb** [comment]
I doubt there is any chance of codecov-bash being included in a distro.

The best chance is by using a bash package manager.

A quick look around shows three bash package managers exist.

http://www.bpkg.io/
https://github.com/ziyaddin/jean
https://github.com/basherpm/basher

None of them exist in Debian or Fedora.

IMO this issue should be closed until a distro has one of those available as a package.
If distro's dont accept a bash package manager, they have even less reason to include a package for codecov-bash

**Comment by jayvdb** [comment]
Note it would be more realistic to get the [python library](https://github.com/codecov/codecov-python) added to more distros, as it already has [a few distros including it](https://repology.org/project/python:codecov/versions), and Python is typically easier to package for distros in a maintainable way, which includes running tests continuously.

**Comment by thomasrockhu** [comment]
Going to close thisout as I don't think we will do it with the bash uploader. You can view progress towards something like this [here](https://github.com/codecov/uploader).
