### ISSUE TITLE
Add support for taskcluster

### ISSUE THREAD

**Issue by pocmo** [codecov/codecov-bash#140]
taskcluster is a task execution framework / CI heavily used by Mozilla:
https://docs.taskcluster.net/docs

We are using codecov for (at least) our Android apps and libraries. Currently we are using travis just for codecov. This has become a bottleneck for us and we would like to run codecov on taskcluster directly (multiple parallel tasks).

I'd like to contribute this - however I do not have a full picture on what is needed for that yet.

**Comment by pocmo** [comment]
Environment variables:
* Default: https://docs.taskcluster.net/docs/reference/workers/docker-worker/docs/environment
* GitHub integration: https://docs.taskcluster.net/docs/reference/integrations/taskcluster-github/docs/taskcluster-yml-v1#transitioning-from-v0

**Comment by pocmo** [comment]
By default this just works with the "git" fallback. However for parallel tasks codecov posts (and updates) the comment on the PR for every task that completed. According to the docs codecov can look at the PR checks status to post the comment once all tasks have been completed. But I'm not sure how codecov does the matching.

**Comment by drazisil** [comment]
@pocmo when `require_ci_to_pass` is set, Codecov will wait for all non-Codecov checks to pass before posting.

You may be looking for `after_n_builds`.

I'd be happy to add this, can you please provide an example of how you would construct a Taskcluster build URL?

**Comment by thomasrockhu** [comment]
I'm going to close this out due to age, but if this is still a need, please open a feature-request on our [community boards](https://community.codecov.io)
