### ISSUE TITLE
What is the your-repository-upload-token?

### ISSUE THREAD

**Issue by lucavallin** [codecov/codecov-bash#143]
I see that I need to add that token there, but nowhere does it say which token and where does it come from.

Is it a Codecov token?
Is it a GitHub token?
It it a TravisCI token?

What token and where do I get it?

**Comment by drazisil** [comment]
Hi @lucavallin 

I hope you figured this out; it is the Codecov upload token shown here https://docs.codecov.io/docs#section-getting-started
