### ISSUE TITLE
Consider adding google cloudbuild as supported CI provider

### ISSUE THREAD

**Issue by scopelf** [codecov/codecov-bash#144]
We are moving from travis to [google cloudbuild](https://cloud.google.com/cloud-build/docs/) as CI and we would love to keep Codecov. Cloudbuild has a list of environment variables, see [here](https://cloud.google.com/cloud-build/docs/configuring-builds/substitute-variable-values),  which seem to be sufficient to run Codecov when comparing them to the environment variables from other supported CI providers, see [here](https://github.com/codecov/codecov-bash/blob/master/env).

**Comment by thomasrockhu** [comment]
I'm going to close this out due to age, but if this is still a need, please open a feature-request on our [community boards](https://community.codecov.io)
