### ISSUE TITLE
failing to upload report to codecov

### ISSUE THREAD

**Issue by goenning** [codecov/codecov-bash#146]
```
/dev/fd/63: line 1: html: No such file or directory
/dev/fd/63: line 2: syntax error near unexpected token `<'
```
By looking at https://github.com/codecov/codecov-bash/issues/59, I suspect this is a codecov issue since nothing has changed on our side.

Source: https://circleci.com/gh/getfider/fider/5068

**Comment by pavelkryukov** [comment]
https://codecov.io/bash returns 503 error page, which starts with ```<html>``` obviously.

**Comment by sirhill** [comment]
I am also having the same issue this morning.
I can also confirm that the server is done with a 503.

Just a strange error message. 😅

/dev/fd/63: line 2: syntax error near unexpected token `<'
/dev/fd/63: line 2: `<html><head>'

**Comment by thomasrockhu** [comment]
Apologies, we are rolling out a fix. You can view the status report [here](https://status.codecov.io/incidents/36hpc8mjhqql)
