### ISSUE TITLE
Cannot use absolute paths when setting the config file via -y

### ISSUE THREAD

**Issue by e-e-e** [codecov/codecov-bash#149]
At the moment the bash script assumes that any file passed via -y is relative to the repo root.

When dynamically generating the yml to be read by codecov we are currently using a temporary file created by mktemp which is not beneath the repo root.

This issue is fixed in the PR - https://github.com/codecov/codecov-bash/pull/147

**Comment by focom** [comment]
+1 this is really needed

**Comment by drazisil** [comment]
@e-e-e Can you merge master into this patch so we can see if the tests pass?

**Comment by thomasrockhu** [comment]
Closing this out as the `-y` flag is deprecated.
