### ISSUE TITLE
can't detect Wercker.

### ISSUE THREAD

**Issue by amondnet** [codecov/codecov-bash#15]
Codecov
    (version) cd5c049
    (url) https://codecov.io
    ==> No CI detected, using git for branch and commit sha.

Wercker Steps - setup enviroment
http://devcenter.wercker.com/docs/environment-variables/available-env-vars.html

     export CI="true" // not True

codecov-bash 

    elif [ "$CI" = "True" ] && [ "$WERCKER_GIT_BRANCH" != "" ];
    then
      say "==> Wercker CI detected."
      # http://devcenter.wercker.com/articles/steps/variables.html
      query="service=wercker\
             &branch=$WERCKER_GIT_BRANCH\
             &build=$WERCKER_MAIN_PIPELINE_STARTED\
             &slug=$WERCKER_GIT_OWNER/$WERCKER_GIT_REPOSITORY\
             &commit=$WERCKER_GIT_COMMIT"

wercker.yml

     export CI="True" // add this line; working properly
     bash <(curl -s https://codecov.io/bash)

**Comment by stevepeak** [comment]
Hey @amondnet thank you for bringing this to my attention. I wonder if they changed the `CI` value from `True` to `true` which threw this off. Thank you :)
