### ISSUE TITLE
`-Z` is not respected if failure occurs during "Uploading Report" step

### ISSUE THREAD

**Issue by carusology** [codecov/codecov-bash#150]
**Background**

According to the documentation, `-Z` should do the following:
> Exit with 1 if not successful. Default will Exit with 0

However, during the "Uploading Report" step, it is possible to get back a `402 PAYMENT REQUIRED` response that looks like the following:
```
HTTP 402
Sorry, but this team has no private repository credits left.
```

When that occurs, the `codecov` script still exits with a code of 0 instead of 1 even when `-Z` is defined.

**Problematic Code**

[Here's a link](
https://github.com/codecov/codecov-bash/blob/4678d212cce2078bbaaf5027af0c0dafaad6a095/codecov#L1553) to the relevant lines of logic, where you can see the script exits with `0` before it has a chance to respect the `${exit_with}` variable that is set via the `-Z` argument.

```bash
exit 0
exit ${exit_with}
```

**Suggestion**

Update the `codecov` script to check for a `4XX` status after it checks for a `5XX` status. If it is found, exit the script using the `${exit_with}` variable. I imagine it would go from this:

```bash
elif [ "${status:0:1}" = "5" ];
then
  say "    ${e}->${x} Sleeping for 30s and trying again..."
  sleep 30

else
  say "    ${g}${res}${x}"
  exit 0
  exit ${exit_with}
fi
```

... to something like this...

```bash
elif [ "${status:0:1}" = "5" ];
then
  say "    ${e}->${x} Sleeping for 30s and trying again..."
  sleep 30

elif [ "${status:0:1}" = "4" ];
then
  say "    ${g}${res}${x}"
  exit ${exit_with}

else
  say "    ${g}${res}${x}"
  exit 0
fi
```

**Comment by thomasrockhu** [comment]
I believe this has been fixed now, let me know if this is not true.
