### ISSUE TITLE
Codecov.io shows wrong coverage after upload using https://codecov.io/bash

### ISSUE THREAD

**Issue by elsid** [codecov/codecov-bash#160]
In [this](https://codecov.io/gh/yandex/ozo/tree/8571d9f8573da63aef23b79a144ce65f65855d00/include/ozo) for [this](https://codecov.io/gh/yandex/ozo/src/8571d9f8573da63aef23b79a144ce65f65855d00/include/ozo/native_conn_handle.h#L19) line codecov.io show zero coverage. But both .gcov files and report sending through [codecov.sh](https://gist.github.com/elsid/aa0a013ed7d2b345882f5803e5c3fd37) contain one record with 100% for this line.
```
# path=build/pg/gcc_coverage/tests/CMakeFiles/ozo_tests.dir/#home#elsid#dev#ozo#include#ozo#native_conn_handle.h.gcov.reduced
        -:    0:Source:/home/elsid/dev/ozo/include/ozo/native_conn_handle.h
40*:19:
_ZNKSt14default_deleteI7pg_connEclEPS0_::
func
40:19:
call    0 returned 100%::
_ZNKSt14default_deleteI7pg_connEclEPS0_::
func
#####:19:
call    0 never executed::
_ZNKSt14default_deleteI7pg_connEclEPS0_::
func
#####:19:
call    0 never executed::
_ZNKSt14default_deleteI7pg_connEclEPS0_::
func
#####:19:
call    0 never executed::
_ZNKSt14default_deleteI7pg_connEclEPS0_::
func
#####:19:
call    0 never executed::
<<<<<< EOF
```

Any ideas why is it so? gcovr html report shows correct coverage for this file.

codecov.sh -t *** [output](https://github.com/codecov/codecov-bash/files/2764179/codecov.log)
codecov.sh -d [output](https://github.com/codecov/codecov-bash/files/2764181/codecov.dump.log)

**Comment by thomasrockhu** [comment]
@elsid, I'm sorry you're seeing that discrepancy and that we are only getting to it now. If you are still seeing this as an issue, please open a ticket in the `support` section of our [community boards](https://community.codecov.io).
