### ISSUE TITLE
Private token gets published with logs (#22)

### ISSUE THREAD

**Issue by Ma124** [codecov/codecov-bash#163]
Like in Issue #22 your private token is printed to stdout.
https://gitlab.com/Ma_124/awesome-framework/-/jobs/156628364

At the moment I use this command to stop this:
```sh
$ bash <(curl -s https://codecov.io/bash) | sed -E 's/token=[A-Fa-f0-9\-]+/token=[codecov token]/g' | sed -e "s/$CODECOV_TOKEN/[codecov token]/g"
```

**Comment by thomasrockhu** [comment]
This has been fixed [here](https://github.com/codecov/codecov-bash/commit/d9f5f8cd1fed2db7a0520773f339a1a7c1d25689#diff-45b1150df0237fb1cb2a238a2d04554eR1508)
