### ISSUE TITLE
Ruby: No coverage report found.

### ISSUE THREAD

**Issue by paveg** [codecov/codecov-bash#166]
## Overview
I could not confirm output than "No coverage report found" .
I think that output is wrong but [script](https://github.com/codecov/codecov-bash/blob/master/codecov#L1010) has already searched `.resultset.json` .

Please, check it.

## Specs
```
- Development Langueage: ruby 2.3.7 and 2.5.3.
- CI: CIRCLE CI 2.0
```

## Example
- [codecov comment post](https://github.com/paveg/oura/pull/7#issuecomment-460290574)
- circleci summary: [summary](https://circleci.com/gh/paveg/oura/81?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link)

```bash
$ #!/bin/bash -eo pipefail
bash <(curl -fs https://codecov.io/bash) -t ${CODECOV_TOKEN}

  _____          _
 / ____|        | |
| |     ___   __| | ___  ___ _____   __
| |    / _ \ / _` |/ _ \/ __/ _ \ \ / /
| |___| (_) | (_| |  __/ (_| (_) \ V /
 \_____\___/ \__,_|\___|\___\___/ \_/
                              Bash-8a28df4


==> Circle CI detected.
    project root: .
    Yaml not found, that's ok! Learn more at http://docs.codecov.io/docs/codecov-yaml
==> Running gcov in . (disable via -X gcov)
==> Python coveragepy not found
==> Searching for coverage reports in:
    + .
    + /tmp/test-results
--> No coverage report found.
    Please visit http://docs.codecov.io/docs/supported-languages
```

**Comment by Henryvw** [comment]
I am also having this exact problem

**Comment by Henryvw** [comment]
In case it's useful to anyone: the documentation for Code Cov is confusing for a simple Rails repo. The Bash script seems to have a problem.

If you remove the Bash script from any CI run list (as the Code Cov orb instructions etc. tell you to do) and let the Codecov gem from the `spec_helper.rb` do the work, it works for me. In other words, ONLY add the gem and activate the gem in `spec_helper.rb` and DON'T include the bash script OR the Orb in the CircleCI `yaml` config.

To debug it in Circle CI, add `- run -ls -la` and `- run env` in the `yaml` config before/after the specs run to check whether the coverage reports are even getting created by `SimpleCov` and/or uploaded.

**Comment by prem-prakash** [comment]
Same problem here

**Comment by dmdashenkov** [comment]
I've been having the samee problem. However, it seems like for Ruby you don't need to use Bash script. Instead the `codecov` Gem does all the uploading itself.

For a simple case with `TestUnit` and `SimpleCov`, this worked for me:
```ruby

require 'test/unit'
require 'simplecov'

# Configure `TestUnit`.
# ...

# Only upload code coverage info from Travis for PR builds.
travis_pr = !ENV['TRAVIS'].nil? && ENV['TRAVIS_PULL_REQUEST'] != 'false'

if travis_pr
  puts 'Building a PR on Travis. Code coverage will run.'
  SimpleCov.start do
    add_filter '/test/'
  end
  require 'codecov'
  SimpleCov.formatter = SimpleCov::Formatter::Codecov
end

exit Test::Unit::AutoRunner.run(true, test_dir)
```

If inspected carefully, this is exactly what the [example](https://github.com/codecov/example-ruby) suggests.

Hope this is helpful to someone.

**Comment by A-Boudi** [comment]
Any news about this issue?

I'm using docker to run my tests. Given that the CI environment variables are not accessible inside docker, I'm extracting the coverage folder after the tests are run. But I can't send them given that the bash script is not supporting ruby simplecov.

**Comment by thomasrockhu** [comment]
I'm going to close this out due to age, but if you are still experiencing issues, please open a ticket in our [community boards](https://community.codecov.io)
