### ISSUE TITLE
Travis-CI macOS environment's `curl` seems cause the codecov uploader failed due to network issue of HTTP/2

### ISSUE THREAD

**Issue by dreampiggy** [codecov/codecov-bash#170]
I'm using codecov with [Travis-CI](https://travis-ci.org/), it provide a macOS environment and I'm developing the iOS/macOS based framework.

Recently (from March maybe), we're facing quite more frequently codecov upload failure issue, it seems about network environment, but have no exact reproduce step. But today, when I try to use `-v` option to see the exact reason, I found the interesting thing.

Please, see the raw log for uploading. It seems there will be a `curl: (56) Unexpected EOF` error during macOS built-in curl uploading.

[log.txt](https://github.com/codecov/codecov-bash/files/3123597/log.txt)

By using the homebrew version of `curl`, this issue disappeared.

**Comment by thomasrockhu** [comment]
@dreampiggy, if this is still an issue, please feel free to open a ticket in the `support` section of our [community boards](https://community.codecov.io).
