### ISSUE TITLE
GitHub releases

### ISSUE THREAD

**Issue by codesuki** [codecov/codecov-bash#171]
We are calling codecov from bazel which uses sha sums to check if a dependency changed. 
Right now the bash script located here https://codecov.io/bash changes for unknown reasons. 
Diffing it shows that there is code from unmerged PRs inside (specifically https://github.com/codecov/codecov-bash/pull/158)

Is there any possibility that you can make releases in the future which we could depend on?
It's not needed since we could disable sha sum checking or just vendor the script but it would be neat. Thanks.

**Comment by blueyed** [comment]
Apparently also the current version (Bash-8a28df4) is not in (public) Git at all?!

**Comment by blueyed** [comment]
I think it is really not good to have something shipped that is not in this public Git repo in the first place, and really makes me want to vendor/sha-checking this myself in projects.

**Comment by drazisil** [comment]
I plan to get a proper pipeline going for this reason, and #186 

For now, https://github.com/codecov/codecov-bash/pull/195/commits/ee8b77c38a585cec90f9b2bebe573e36b7a482bc is the current file in production.

**Comment by thomasrockhu** [comment]
We will be now be creating GitHub releases.
