### ISSUE TITLE
codecov upload suddenly stopped working, no error message

### ISSUE THREAD

**Issue by HDembinski** [codecov/codecov-bash#176]
I have been using Codecov successfully in [Boost.Histogram](https://github.com/boostorg/histogram) until a few days ago, when it stopped working. I don't know how to fix this, because I am seeing no error message.

You can see here in my Travis job, that the coverage data is generated and successfully uploaded without any errors:
https://travis-ci.org/boostorg/histogram/jobs/543750004#L898

But when I go to the Codecov page, it reports an unspecified error: "There was an error processing coverage reports."
https://codecov.io/github/boostorg/histogram/commit/7e40aaf68997a6febe575d44f64b1992e320eafc

I am good at debugging problems but this situation gives me nothing to work with. I checked the upload report with the `-d` option and it looks ok to me.

**Comment by HDembinski** [comment]
I should add that it stopped working globally. Even when I check out an older commit that used to generate a coverage report, I now get the same error message for that commit.

**Comment by drazisil** [comment]
This is generally a server-side issue, not an uploader one.

I hope you are not still affected by this, but if so can you please open a ticket (if paid) so we can investigate?
