### ISSUE TITLE
Issues using "-f" option

### ISSUE THREAD

**Issue by pydolan** [codecov/codecov-bash#177]
I was trying to upload coverage reports whose file names started with `.coverage` (e.g., `.coverage-unit-part1` and `.coverage-unit-part2`) and the uploader couldn't find any results. 

Looking at the source for the uploader, I see an [exclusion](https://github.com/codecov/codecov-bash/blob/master/codecov#L1066) for files that start with ".coverage", so if this is related, maybe don't do the exclude if using the -f option?

Example of command: `bash <(curl -s https://codecov.io/bash) -Z -f '.coverage-unit-*' -F unittests`

I then tried renaming the files without the proceeding period (e.g., `coverage-unit-part1` and `coverage-unit-part2`) but my command then finds more files than I want:

`bash <(curl -s https://codecov.io/bash) -Z -f 'coverage-unit-*' -F unittests` --includes the "-unit" files, but also includes "-integration" files (e.g., `coverage-integration-part1` and `coverage-integration-part2`)

**Comment by thomasrockhu** [comment]
@pydolan, if this is still an issue, please open a ticket in the `support` section of our [community boards](https://community.codecov.io).
