### ISSUE TITLE
The token is written out to logs

### ISSUE THREAD

**Issue by hjpotter92** [codecov/codecov-bash#182]
> Cross posting from codecov/codecov-circleci-orb#18 

---

This is the output from when coverage is uploaded using the orb:

```
#!/bin/bash -eo pipefail
curl -s https://codecov.io/bash | bash -s -- \
  -f "./coverage.xml" \
  -t "${CODECOV_TOKEN}" \
  -n "${CIRCLE_BUILD_NUM}" \
  -y ".codecov.yml" \
  -F "django,backend" \
  -Z || echo 'Codecov upload failed'

  _____          _
 / ____|        | |
| |     ___   __| | ___  ___ _____   __
| |    / _ \ / _` |/ _ \/ __/ _ \ \ / /
| |___| (_) | (_| |  __/ (_| (_) \ V /
 \_____\___/ \__,_|\___|\___\___/ \_/
                              Bash-8a28df4


==> Circle CI detected.
    project root: /home/circleci/repo
    Yaml found at: .codecov.yml
    -> Found 1 reports
==> Detecting git/mercurial file structure
==> Reading reports
    + ./coverage.xml bytes=528972
==> Appending adjustments
    http://docs.codecov.io/docs/fixing-reports
    + Found adjustments
==> Gzipping contents
==> Uploading reports
    url: https://codecov.io
    query: branch=support%2Ftest&commit=c7b8107b96d9b77f32d5c307aaa1b5946e661a8b&build=11868&build_url=&name=11868&tag=&slug=test%2Frepo&service=circleci&flags=django,backend&pr=&job=0
    -> Pinging Codecov
https://codecov.io/upload/v4?package=bash-8a28df4&token=<<TOKEN-LIES-HERE>>&branch=support%2Ftest&commit=c7b8107b96d9b77f32d5c307aaa1b5946e661a8b&build=11868&build_url=&name=11868&tag=&slug=test%2Frepo&service=circleci&flags=django,backend&pr=&job=0
    -> Uploading
    -> View reports at https://codecov.io/github/test/repo/commit/c7b8107b96d9b77f32d5c307aaa1b5946e661a8b
```

The section `<< TOKEN-LIES-HERE >>`  is output to the logs, and is visible for anyone to read.

Most likely due to the echo statement here: https://github.com/codecov/codecov-bash/blob/4678d212cce2078bbaaf5027af0c0dafaad6a095/codecov#L1495

**Comment by artplan1** [comment]
@hjpotter92 are you sure this issue exists because according to https://github.com/codecov/codecov-bash/blob/master/codecov#L1508 it should output `token=secret`

**Comment by hjpotter92** [comment]
@artplan1 compare the logs above with the code segment:

https://github.com/codecov/codecov-bash/blob/4678d212cce2078bbaaf5027af0c0dafaad6a095/codecov#L1489-L1495

**Comment by artplan1** [comment]
provided code is not latest. Deployed version has different code with `queryNoToken`

**Comment by hjpotter92** [comment]
But as you can see, there is no `say` call after `say "    ${e}->${x} Pinging Codecov"` in the old code, yet the url is being written out. Most likely (as mentioned in my first comment in this thread) it is due to the `echo` statement later:

    status=$(echo "$res" | head -1 | grep 'HTTP ' | cut -d' ' -f2)

**Comment by espipj** [comment]
As @artplan1 said, the provided version of the code is not the latest where it is fixed:
https://github.com/codecov/codecov-bash/blob/master/codecov#L1515-L1526
