### ISSUE TITLE
Please provide a digital signature

### ISSUE THREAD

**Issue by szepeviktor** [codecov/codecov-bash#186]
See the real danger in https://twitter.com/pear/status/1086634389465956352
and https://github.com/pypa/get-pip/issues/41

Related https://github.com/codecov/codecov-bash/issues/171

**Comment by szepeviktor** [comment]
You could consider placing the bash script and the signature on very different platforms.

**Comment by szepeviktor** [comment]
@drazisil Thank you for providing the hash.

Could you make it available for a script too?

**Comment by drazisil** [comment]
@szepeviktor   Could you describe more what you are looking for? Do you mean as a separate, fetchable file?

**Comment by szepeviktor** [comment]
@drazisil Yes. Please see the link at the top. I would be ideal to host the bash script on infrastructure ans the hash on another one.
