### ISSUE TITLE
Frequent platform unavailability

### ISSUE THREAD

**Issue by wilzbach** [codecov/codecov-bash#188]
![image](https://user-images.githubusercontent.com/4370550/62668910-ee3ccc80-b98d-11e9-848c-b8ec3211ebcf.png)

https://circleci.com/gh/storyscript/storyscript/565

Happens very often lately.

**Comment by blueyed** [comment]
Not an issue with codecov-bash itself.

**Comment by PhilippeBoisney** [comment]
Same problem here...  
![image](https://user-images.githubusercontent.com/6847959/62858864-d0f45f00-bcfb-11e9-9727-dc844bee7bc2.png)

**Comment by vearutop** [comment]
Same for me, failing/retrying to upload to `codecov` takes more time than actual tests!
@blueyed do you mind directing to a proper place for support?

**Comment by thomasrockhu** [comment]
@vearutop if you are still seeing this problem, please open an issue at community.codecov.io

**Comment by PhilippeBoisney** [comment]
The opened issue: https://community.codecov.io/t/upload-timeouts/448
