### ISSUE TITLE
-x option ignored

### ISSUE THREAD

**Issue by texus** [codecov/codecov-bash#19]
Since commit 72c885f the script always uses the "gcov" executable instead of using the executable name provided with the -x parameter. Since I use gcc 5 in my project I need to execute "gcov-5" on travis.

After taking a quick look at the code it also looks as if the gcov arguments are ignored in the latest version since it has $gcovargs instead of $gcov_arg ([line 486](https://github.com/codecov/codecov-bash/blob/08fbbe6c1fe2f66a6c364f6c206045cb370be35a/codecov#L486)) and the osx line ([line 462](https://github.com/codecov/codecov-bash/blob/08fbbe6c1fe2f66a6c364f6c206045cb370be35a/codecov#L462)) doesn't have either, but I'm not familiar enough with the script to say if this is wrong or not.

**Comment by stevepeak** [comment]
Sorry about this issue. I've deployed a fix just now. Thank you!
