### ISSUE TITLE
Upload from Azure Pipelines fails for 10 minutes

### ISSUE THREAD

**Issue by Pr0methean** [codecov/codecov-bash#197]
On Microsoft-hosted Azure Pipelines, uploads often fail repeatedly for several minutes. Here is one example:

[log_119_960.zip](https://github.com/codecov/codecov-bash/files/3517757/log_119_960.zip)

This seems to happen more often if I've been running a lot of tests in recent hours. Today I was running the unit tests more than usual and uploading more than usual, because the unit tests were passing on some environments and failing on others. (When the unit tests pass in _all_ environments, most of the VM hours are spent on longer tests which are gated on the unit tests; and when they fail in all, there are no reports to upload.) Still, I've never had more than 10 uploads going in parallel, because that's how many VMs Microsoft provides.

**Comment by Trim21** [comment]
Same issues...

I have a stage with 10 jobs, and one of them frequently got `Failed to upload` and take about 10 minutes to upload.

**Comment by codecog** [comment]
"Failed to upload, sleeping for 30 seconds". Takes around 9-10 minutes for this step of my CI pipeline to complete.

**Comment by jfboismenu** [comment]
Originally I was not using the CODECOV_TOKEN env var and everything seemed to be working. Then I some point I started having numerous failures to upload like you did @Trim21 and @Pr0methean . At some point I tried setting CODECOV_TOKEN and it has been working ever since.

**Comment by codecog** [comment]
I ended up moving away from using bash and went with the node runner. No issue then and works every time.

**Comment by Pr0methean** [comment]
@jfboismenu  CODECOV_TOKEN *is* set in my build. If it was set incorrectly, would the script tell me so?

**Comment by thomasrockhu** [comment]
I'm going to close this as we have made significant changes to our infrastructure around timeout failures. If this is still an issue, please open a ticket in the `support` section of our [community boards](https://community.codecov.io).
