### ISSUE TITLE
Statement coverage not sent completely

### ISSUE THREAD

**Issue by VladUreche** [codecov/codecov-bash#2]
This is what I get on codacy: https://www.codacy.com/app/vladureche/miniboxing/file/638296884/coverage?bid=2211210&fileBranchId=2211210 (it's not showing missed statements, only the ones hit) and here's what I get on codecov: https://codecov.io/github/miniboxing/miniboxing-plugin/components/plugin/src/miniboxing/plugin/transform/minibox/inject/MiniboxDuplTreeTransformation.scala?ref=wip

I tried to debug the bash script, but afaict it's pushing all the data to the server. Maybe I'm wrong...

**Comment by stevepeak** [comment]
On your local machine can you run the bash script as this: `codecov -vd` and send me the results. I'll review the coverage documents to see whats up. Thanks!

**Comment by VladUreche** [comment]
Thanks for looking into this!
Here it is: https://gist.github.com/VladUreche/75b3d9693ca1f50106b9

**Comment by stevepeak** [comment]
Thanks, I'll review this first thing tomorrow and get back to you.

**Comment by VladUreche** [comment]
Thanks @stevepeak!

**Comment by stevepeak** [comment]
@VladUreche there are some new report formats I have not encountered before. I'll have this fixed up for you today. I'll be in touch in your Gitter room when I'm ready for a new upload. Sound good? Thanks!
