### ISSUE TITLE
Coverage reports not applying across modules

### ISSUE THREAD

**Issue by macgills** [codecov/codecov-bash#210]
I have run into a problem with the modularisation of [kiwix](https://github.com/kiwix/kiwix-android) in particular on this [PR](https://github.com/kiwix/kiwix-android/pull/1541).

We rely on the coverage reports generated by our unit tests and instrumented tests to get the overall report for the project. This worked great (thanks a lot btw) on a single app module as the tests instrumented/unit lived in the same place as the code under test.

In the new scenario I have pulled all app code into a library called `core` and `app/custom` are thin modules over this to present 2 different apps. The gotcha is that instrumented tests can't live in the library codebase and must be in `app` as a library is not a runnable app.
This results in the coverage report being generated at `./app/build/reports/coverage/debug/report.xml` that is required to be applied to `core`. In my [travis build](https://travis-ci.org/kiwix/kiwix-android/builds/593425045) I have tried just copying this report into a similar directory under `core` and it was picked up by codecov but my coverage still fell by 28%. This could have been misguided, I am unsure on the intended usage of [path fixes](https://docs.codecov.io/docs/fixing-paths) but I want the coverage report to apply to both `app` and `core` as I will be gradually moving functionality -as appropriate- from `core` into `app`.

Any advice on this issue would be appreciated.

**Comment by kayleneciman** [comment]
Don’t agree

**Comment by macgills** [comment]
@kayleneciman could you elaborate?

**Comment by macgills** [comment]
From my own SO question https://stackoverflow.com/questions/58415184/is-it-possible-for-instrumented-tests-to-create-coverage-for-a-library-module/58435071#58435071 pretty sure it is just impossible. Put your tests in the right module.
