### ISSUE TITLE
Codecov.io UI not resolving submodule paths in GitHub

### ISSUE THREAD

**Issue by Dagefoerde** [codecov/codecov-bash#215]
Hi,
I have a configuration that (maybe excessively...) makes use of submodules. I can generate, upload, and view coverage reports that were generated on Travis-CI and uploaded to codecov.io. However, the web UI at codecov.io only gives me an overview. I cannot enter single files and view their line coverage.

For instance: https://codecov.io/gh/wwu-pi/muli/src/aa6f1697a4dd513d1f3f811cf72b2f43c18cf4ac/muli-env/muli-runtime/src/main/java/de/wwu/muli/iteratorsearch/BreadthFirstSearch.java.

The path fix already ensures that this points to a path that works in the main repo https://github.com/wwu-pi/muli (branch [free-objects](https://github.com/wwu-pi/muli/tree/free-objects)). However, codecov.io says that the path cannot be resolved, even though it exists and all submodules are public.

Sorry if this was not the right place to report this! I didn't know any better, but at least the bash script really was my uploader...

Thanks all!

**Comment by drazisil** [comment]
Hi @Dagefoerde 

In the future, please file non-uploader bugs in our community at https://community.codecov.io/c/bug-fixes

I'll be closing this issue, but I did share it with the engineering team so they are aware.

**Comment by Dagefoerde** [comment]
Hi Joe, 
Of course! Thanks for caring and for forwarding it to the right people. By any chance, is there a link to a place where I can track the progress of this issue? Thanks again.

**Comment by drazisil** [comment]
There isn't,  publicly, but if you can create a community post i can link it internally so we can let you know when there's an update.

**Comment by Dagefoerde** [comment]
That would be wonderful. Here you go: https://community.codecov.io/t/codecov-io-ui-not-resolving-submodule-paths-in-github/713 Thanks and sorry again.
