### ISSUE TITLE
[CE-919] Add support for CodeBuild CI

### ISSUE THREAD

**Issue by trivikr** [codecov/codecov-bash#216]
Refs: https://github.com/codecov/codecov-node/issues/139#issuecomment-546433239

This should be similar to https://github.com/codecov/codecov-bash/pull/199

**Comment by trivikr** [comment]
Refs: https://github.com/codecov/codecov-node/issues/152

**Comment by trivikr** [comment]
Any update on this request?

**Comment by drazisil** [comment]
Merged, waiting on deploy, will let you know when.

**Comment by trivikr** [comment]
Any update on deployment?

**Comment by drazisil** [comment]
Yes, thank you for your patience. I was on vacation last week, but i confirmed today that this has been deployed.

**Comment by drazisil** [comment]
This has been deployed, Thank you for your patience.
