### ISSUE TITLE
Bug with if statement according to shell's standards

### ISSUE THREAD

**Issue by ysaunier** [codecov/codecov-bash#221]
Hi team,

There is a little error with this if statement for the pull request number.
Ref: [codecov/codecov-bash#L755](https://github.com/codecov/codecov-bash/blob/416cd419528f74f77fbb4542241a0a79475cfc47/codecov#L775)

Should be : 
```
if [ -z "$PULL_REQUEST_NUMBER" ];
```

**Comment by drazisil** [comment]
Hi @ysaunier 

PRs welcome. It looks like it's a single space, am I correct?

Can you link me to these standards for bash you are quoting, I'd love to take a look.

**Comment by thomasrockhu** [comment]
Closing as I don't believe this is relevant anymore.
