### ISSUE TITLE
Bitbucket Pipelines Support

### ISSUE THREAD

**Issue by KajdeMunter** [codecov/codecov-bash#223]
Something went wrong with https://github.com/codecov/codecov-bash/pull/135 and now the `env` file does not contain a check for bitbucket.

I can create a PR if interested.

**Comment by drazisil** [comment]
Hi @KajdeMunter 

It seems like it's here: https://github.com/codecov/codecov-bash/blob/master/tests/env#L107-L111

Can you explain more about what you see missing?

**Comment by drazisil** [comment]
Never mind, I missed that #225 was linked, taking a look now.
