### ISSUE TITLE
Broken pipe when appending adjustments

### ISSUE THREAD

**Issue by leofeyer** [codecov/codecov-bash#226]
When running the bash uploader in a GitHub action, an error occurs in the "Appending adjustments" step: `/dev/fd/63: line 1451: echo: write error: Broken pipe` This does not seem to affect the coverage stats on codecov.io. though.

```
Run bash <(curl -s https://codecov.io/bash) -f clover.xml

  _____          _
 / ____|        | |
| |     ___   __| | ___  ___ _____   __
| |    / _ \ / _` |/ _ \/ __/ _ \ \ / /
| |___| (_) | (_| |  __/ (_| (_) \ V /
 \_____\___/ \__,_|\___|\___\___/ \_/
                              Bash-20191111-ecb75bd

==> GitHub Actions detected.
    project root: .
--> token set from env
    Yaml found at: codecov.yml
    -> Found 1 reports
==> Detecting git/mercurial file structure
==> Reading reports
    + clover.xml bytes=588360
==> Appending adjustments
    http://docs.codecov.io/docs/fixing-reports
/dev/fd/63: line 1451: echo: write error: Broken pipe
    + Found adjustments
==> Gzipping contents
==> Uploading reports
    url: https://codecov.io
    query: branch=refs%2Fpull%2F977%2Fmerge&commit=735884174a1174a5f06b1e7a66c4c26ea38ac265&build=&build_url=&name=&tag=&slug=contao%2Fcontao&service=github-actions&flags=&pr=&job=run3
    -> Pinging Codecov
https://codecov.io/upload/v4?package=bash-20191111-ecb75bd&token=secret&branch=refs%2Fpull%2F977%2Fmerge&commit=735884174a1174a5f06b1e7a66c4c26ea38ac265&build=&build_url=&name=&tag=&slug=contao%2Fcontao&service=github-actions&flags=&pr=&job=run3
    -> Uploading
    -> View reports at https://codecov.io/github/contao/contao/commit/3c1365f483c1044c62dd23113e7987a399d1ad74
```

The error occurs in line 1451:

https://github.com/codecov/codecov-bash/blob/ecb75bd56eb54daa825c8d9963a40c7da0698df8/codecov#L1451

Any idea what causes the issue and how I can solve it?

**Comment by Kaspik** [comment]
+1 to this issue, it _seems_ like it's not breaking anything, but I believe it might be cause of random failures of the upload.

```
==> Appending adjustments
303
    http://docs.codecov.io/docs/fixing-reports
304
/dev/fd/13: line 1531: echo: write error: Broken pipe
305
    + Found adjustments
306
==> Gzipping contents
```

@drazisil Any timeline for this?

**Comment by drazisil** [comment]
Hi @leofeyer , @Kaspik 

I did some research on this a while back, then went on sick leave and forgot about it.

The details are covered here: https://unix.stackexchange.com/questions/156084/why-does-process-substitution-result-in-a-file-called-dev-fd-63-which-is-a-pipe

I don't believe it would account for the upload issues. We have a pretty good idea what causes those but every case is different. If you are having issues with uploads I ask that you let us know at community.codecov.io, or open a ticket if you are a paying customer.

Regarding this issue, PRs are welcome if you want to tackle this (not that good at bash myself)

**Comment by Kaspik** [comment]
Adding one more example of the failure (might not be related as you said):

```
8159 /dev/fd/13: line 1626: echo: write error: Broken pipe
8160 -> Uploading
8161 X> Failed to upload
8162 -> Sleeping for 30s and trying again...
8163 -> Uploading to Codecov
8164 HTTP 400
8165 pr must match pattern ^(\d+|false|null|undefined|true)$
```

**Comment by drazisil** [comment]
@Kaspik 

That's completely different. What is the PR value in this case? It should just be the number, no letters or symbols

**Comment by Kaspik** [comment]
PR #5438 in private repo.

**Comment by drazisil** [comment]
No, in the upload query url. You dont need to share it, check if it matches that regex though. If not, you need to figure out why.

**Comment by Kaspik** [comment]
I'm okay with sharing the output, there is nothing secret (and `token` is actually hidden). The weird thing is that the same run works on Re-run of the same commit usually.

```
8157 Pinging Codecov
8158 https://codecov.io/upload/v4?package=bash-tbd&token=secret&branch=messaging%2FInboxAccessibility&commit=f413d9771943fae3efbfbe2078f4c719103f8723&build=103596106&build_url=http%3A%2F%2Fgithub.com%2Fclassdojo%2Fdojo-behavior-ios%2Factions%2Fruns%2F123456789&name=&tag=&slug=classdojo%2Fdojo-behavior-ios&service=github-actions&flags=tests_ci&pr=refs/heads/messaging/InboxAccessibility&job=
8159 /dev/fd/13: line 1626: echo: write error: Broken pipe
8160 -> Uploading
8161 X> Failed to upload
8162 -> Sleeping for 30s and trying again...
8163  -> Uploading to Codecov
8164 HTTP 400
8165 pr must match pattern ^(\d+|false|null|undefined|true)$
```

CI is using `zsh` as default shell as it's macOS machine and `zsh` is default on Catalina.

**Comment by drazisil** [comment]
`pr=refs/heads/messaging/InboxAccessibility`

This is not a valid PR number, something is messing with the envs being checked here https://github.com/codecov/codecov-bash/blame/master/codecov#L772-L778

This is not related to the original issue though, can you please move this issue to community.codecov.io if you are unable to solve it?

**Comment by Kaspik** [comment]
Okay, there is still the error with broken pipe - so it's apparently multiple places.

For the second issue with HTTP 400, I created separate topic there: https://community.codecov.io/t/error-http-400-pr-must-match-pattern-github-actions/1411

**Comment by brechtm** [comment]
In my CI runs, the broken pipe error seems to correspond to  coverage reports where different paths from different jobs aren't being detected as equivalent. For example: [this report](https://codecov.io/gh/brechtm/rinohtype/tree/8b80a38f61d9f48c521fea908b9b2d026b196ed3).

**Comment by thomasrockhu** [comment]
@brechtm going to close this out. Can you open a ticket under `support` in our [community boards](https://community.codecov.io)? Also, thanks for bringing up this issue which is slightly different than the original problem here.

**Comment by brechtm** [comment]
> @brechtm going to close this out. Can you open a ticket under `support` in our [community boards](https://community.codecov.io)? Also, thanks for bringing up this issue which is slightly different than the original problem here.

The coverage reports for new commits do not exhibit the merging issue. I'll open a ticket on the community boards if the issue pops up again. Cheers!
