### ISSUE TITLE
HTTP 400 Invalid signature

### ISSUE THREAD

**Issue by nuhkoca** [codecov/codecov-bash#227]
Hi all,

I am not sure if this is the right place for this. In any inconvenience, please let me know.

I am uploading my report via `CircleCI` and it generally finishes successfully. However, my reports are not uploaded on my repository under [codecov.io](https://codecov.io/gh)

**CircleCI config**

```
version: 2.1
orbs:
  codecov: codecov/codecov@1.0.5
jobs:
  build:
    ...
    environment:
   ...
    steps:
     ...
      - codecov/upload:
          file: report.xml
          flags: android
```

**CircleCI response**

```
==> Circle CI detected.
    project root: .
    Yaml found at: .codecov.yml
    -> Found 1 reports
==> Detecting git/mercurial file structure
==> Reading reports
    + report.xml bytes=113994
==> Appending adjustments
    http://docs.codecov.io/docs/fixing-reports
    + Found adjustments
==> Gzipping contents
==> Uploading reports
    url: https://codecov.io
    query: xxx
    -> Pinging Codecov
xxx
    -> Uploading
    -> View reports at xxx
```

However, webhook throws below error:

```
HTTP 400
Invalid signature
```

**Deliver request**

```
Request URL: https://codecov.io/webhooks/github
Request method: POST
content-type: application/json
Expect: 
User-Agent: GitHub-Hookshot/f1003bc
X-GitHub-Delivery: 0e89016e-071a-11ea-8525-xxx
X-GitHub-Event: status
X-Hub-Signature: sha1=32a9xxx
```

It would be appreciated if you help me. Thanks in advance!

**Comment by nuhkoca** [comment]
**Update**

Now it works but webhook response includes;

> Ok. Skip because commit not found or is processing.

In addition to that, I am unable to see my coverage on [codecov.io](https://codecov.io/). It says;

**There was an error processing coverage reports.**

**Comment by drazisil** [comment]
Hi @nuhkoca 

This is a server side issue, not an uploader one. I believe it's this issue https://community.codecov.io/t/open-issue-investigation-report-stuck-in-processing-unable-to-find-report-content-in-storage-archive/670/2

If you can follow the directions in that post and provide us your information we can investigate.
