### ISSUE TITLE
Cannot upload report to S3

### ISSUE THREAD

**Issue by pvorb** [codecov/codecov-bash#23]
Here's my full output of calling codecov-bash:

~~~
$ bash <(curl -s https://codecov.io/bash) -p $CI_PROJECT_DIR -t $codecov_upload_token || echo "Codecov did not collect coverage reports"

  _____          _
 / ____|        | |
| |     ___   __| | ___  ___ _____   __
| |    / _ \ / _` |/ _ \/ __/ _ \ \ / /
| |___| (_) | (_| |  __/ (_| (_) \ V /
 \_____\___/ \__,_|\___|\___\___/ \_/
                                5ca7b8c


(url) https://codecov.io
(root) .
==> GitLab CI detected.
==> Trying gcov (disable via -X gcov)
  -> Running gcov
==> Searching for coverage reports
**> Python coverage not found
==> Detecting git/mercurial file structure
==> Reading reports
  + ./target/site/jacoco/jacoco.xml bytes=2806
(query) package=bash-5ca7b8c&branch=feature/codecov&commit=1921b64c41af1819966877003ba9e1780da9cf45&build=640303&build_url=&slug=pvorblab-ci-java-gradle-codecov.git&service=gitlab&pr=&job=&token=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
==> Uploading reports
    Pinging Codecov
    Uploading to S3
Codecov did not collect coverage reports
~~~

I obfuscated the token in the output (see #22).

What might be the cause of the problem? I can't really tell from the output, but the code tells me that either "Reports queued to [...]" or "Failed to upload to s3" should be printed after "Uploading to S3".

**Comment by stevepeak** [comment]
I found the error in out logs. Looks like the issue is due to the `slug` argument.
```
slug=pvorblab-ci-java-gradle-codecov.git
```

This value should be something like `owner/repo`. Looks like it is not being detected properly in GitLab.

I'll review more and get back to you shortly. Thankssteve@stevepeak.net

**Comment by pvorb** [comment]
Thank you for the update.

The repository's name actually is `pvorb/gitlab-ci-java-gradle-codecov.git`, so it actually is `owner/repo` . A possible explanation could be a regex `/.git/` which is replaced by an empty string.

**Comment by stevepeak** [comment]
Thanks :) I'll be putting this live soon. Just need to fix some CI tests around it. Cheers!
