### ISSUE TITLE
Investigate way to automatically generate hash

### ISSUE THREAD

**Issue by drazisil** [codecov/codecov-bash#231]
I would like a more automated way to generate the sha1sum.

**Comment by thomasrockhu** [comment]
I'm not sure you meant something like https://github.com/codecov/codecov-bash/pull/391 or not @drazisil, but here you are

**Comment by drazisil** [comment]
Yes, this is what I had in mind, thanks.

**Comment by thomasrockhu** [comment]
Fixed in #391
