### ISSUE TITLE
Typescript optional chaining

### ISSUE THREAD

**Issue by maxim-pushchinskiy** [codecov/codecov-bash#236]
Hi. Maybe I do something wrong, but I didn't find any configuration options to solve this problem. Seems, that `codecov` has wrong coverage calculation for typescript optional chaining. For example:
```
public isSameUser = (userId: string): boolean => {
    return this.user?.id === userId;
}
``` 
test for that
```
it('should return true if it is the same user', () => {
    const newUser = entityBuilder.createUser();
    expect(session.isSameUser(session.user.id)).toBeTruthy();
    expect(session.isSameUser(newUser.id)).toBeFalsy();
    expect(session.isSameUser(null)).toBeFalsy();
  });
```
but coverage is still 50 %

<img width="529" alt="Screen Shot 2019-12-02 at 18 18 23" src="https://user-images.githubusercontent.com/20857095/69975661-45b00b00-1530-11ea-9939-90f441286192.png">

**Comment by maxim-pushchinskiy** [comment]
Sorry, forgot to explain, that optional chaining is the new feature of typescript  https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html#optional-chaining

**Comment by drazisil** [comment]
Codecov doesn't generate the coverage report, this may need to be filed as an issue with the test coverage reporting you are using.

**Comment by thomasrockhu** [comment]
Partial matches are also considered uncovered. Going to close this out @maxim-pushchinskiy. If this is still an issue, we can take a look if you open a ticket in our [community boards](https://community.codecov.io).
