### ISSUE TITLE
Token priority: parameter, env var or yaml?

### ISSUE THREAD

**Issue by hugovk** [codecov/codecov-bash#238]
There are at least three ways to give the token:

* Parameter: `bash <(curl -s https://codecov.io/bash) -t my_uuid`
  * Or `-t @/path/to/token_file`

* Environment variable: `CODECOV_TOKEN=my_uuid; bash <(curl -s https://codecov.io/bash)`

* In `.codecov.yml`: 
```yml
codecov:
  token: my_uuid
```

If the token is given in more than one place, which one is used first? Which is the second choice and which last?

**Comment by hugovk** [comment]
Looks like the priority is:

1. param-token
2. env-token
3. yaml-token

From some tests with editing the script to output the token, and trying some combos:

A

✅ param-token
❌ env-token

B

✅ param-token
❌ env-token
❌ yaml-token

C

✅ env-token
❌ yaml-token

D

✅ param-token
❌ yaml-token

**Comment by drazisil** [comment]
That is correct, verified by looking at the code.
