### ISSUE TITLE
Bitbucket Pipelines not setting full SHA

### ISSUE THREAD

**Issue by drazisil** [codecov/codecov-bash#241]
This is (part of) `printenv` (with OMISSIS on sensitive data):

```
BITBUCKET_COMMIT=3fffce06e9e2

```

_Originally posted by @Slamdunk in https://github.com/codecov/codecov-bash/pull/225#issuecomment-562528019_

**Comment by drazisil** [comment]
This has been raised with Bitbucket here: https://jira.atlassian.com/browse/BCLOUD-19393, is currently not a high priority to fix.

https://github.com/codecov/codecov-bash/pull/225#issuecomment-562547224

**Comment by drazisil** [comment]
Current workaround is to pass the uploader the commit SHA manually using `-C <SHA>`

https://github.com/codecov/codecov-bash/blob/master/codecov#L167

**Comment by Slamdunk** [comment]
I can confirm the workaround:
![immagine](https://user-images.githubusercontent.com/152236/70421813-e2136980-1a6a-11ea-9fb5-f5816b08f009.png)

**Comment by Slamdunk** [comment]
@drazisil I don't trust Bitbucket enough to hope anything will move before next century: will you accept a PR to incorporate the workaround into codecov-bash?

**Comment by drazisil** [comment]
Yep, if you code it and it passes tests, i will accept.

**Comment by drazisil** [comment]
This is resolved by #247 , thanks to @Slamdunk
