### ISSUE TITLE
(3) Illegal characters found in URL on Upload API - Azure

### ISSUE THREAD

**Issue by pilomat** [codecov/codecov-bash#253]
I've been having trouble when using the bash uploader with Azure Pipeline.

Specifications: 
- JaCoco
- Maven

Here is the upload command I'm using for Azure-Pipeline.
`- bash: bash <(curl -s https://codecov.io/bash) -v
`

This is the no- verbose log:

`    -> Uploading
    X> Failed to upload
    -> Sleeping for 30s and trying again...
    -> Uploading to Codecov
    -> Sleeping for 30s and trying again...
    -> Sleeping for 30s and trying again...
    -> Sleeping for 30s and trying again...
    -> Sleeping for 30s and trying again...
    X> Failed to upload coverage reports
`
I've already tried to follow this way #148, unfortunately it doesn't work.

Morerover, running it in a verbose mode I found this particular error:

 `
++ curl -X POST -H 'X-Reduced-Redundancy: false' -H 'X-Content-Type: application/x-gzip' 'https://codecov.io/upload/v4?package=bash-20191211-b8db533&token=some-token-uuid
&branch=dev-sca-sonar-scanner&commit=1f27877d08838e19e95571e4a084f0932a8259e1&build=20200114.29&build_url=https%3A%2F%2Fdev.azure.com%2FCompanyName%2Fdevops-demo%2F_build%2Fresults%3FbuildId%3D125&name=&tag=&slug=pippoComp%2Fdevops-demo&service=azure_pipelines&flags=&pr=&job=125&project=devops-demo&server_uri=https://dev.azure.com/CompanyLab/'

curl: (3) Illegal characters found in URL
`

**Comment by drazisil** [comment]
Nothing looks out of place with that URI. Are you able to run that curl command locally without errors?

**Comment by thomasrockhu** [comment]
Closing this out from age, @pilomat if this is still an issue, please open a ticket in our [community boards](https://community.codecov.io)
