### ISSUE TITLE
Create an option to only output SHA for use in downstream CI jobs

### ISSUE THREAD

**Issue by drazisil** [codecov/codecov-bash#254]
Create an option to only detect and output the commit SHA for saving and passing back to the bash uploader via the `-C` flag in downsteam jobs where the .git repo is not present.

Note, this requires investigation since, whithout the source code, the bash uploader is unable to build the network section of the upload and Codecov may encounter issues parsing the report.

**Comment by thomasrockhu** [comment]
@drazisil, I'm not sure I understand this one.

**Comment by drazisil** [comment]
I know the use case, not sure how common it is.

In a multi-job build, the files and test coverage may be persisted and run in a later job where there is no .git repo, and thus the uploader does not know the commit.

The ask, and I don't remember the source, was a way to have the uploader output the bare SHA to a file for use in that later upload job.

This can easily be done with a raw git command as well. I'm closing.
