### ISSUE TITLE
Unexpected behavior of informational flag

### ISSUE THREAD

**Issue by code-schreiber** [codecov/codecov-bash#269]
I'm having trouble using the `informational` flag in Codecov's configuration file:

![Screenshot 2020-02-25 at 12 04 53](https://user-images.githubusercontent.com/759086/75241956-74541f80-57c7-11ea-8842-f6de5860c84e.png)

Taking the info provided by the docs that should be enough to be able to merge a pull request without having Codecov's "check"
https://docs.codecov.io/docs/commit-status#section-informational

> Informational mode is great to use if you want to expose codecov information to other developers in your pull request without necessarily gating PRs on that information. 

But it seems to still block PRs, what could I be missing?

![Screenshot 2020-02-25 at 12 05 49](https://user-images.githubusercontent.com/759086/75241958-74ecb600-57c7-11ea-91bd-d32e80743a22.png)

**Comment by d-luk** [comment]
Same problem here. Seems to be a bug.

**Comment by thomasrockhu** [comment]
Due to the age of this issue I'm going to close out. If this is still an issue, please open a ticket in our [community boards](https://community.codecov.io)
