### ISSUE TITLE
Whitespace not rendering before URL (Cirrus CI)

### ISSUE THREAD

**Issue by jayvdb** [codecov/codecov-bash#273]
https://cirrus-ci.com/task/5957768351842304?command=main#L61 shows the follow message, but the whitespace between "at" and the URL is not shown when the entire line is not broken.

> Yaml not found, that's ok! Learn more at http://docs.codecov.io/docs/codecov-yaml

When I copy the line, the space is there.

There is whitespace in https://github.com/codecov/codecov-bash/blob/c71e656/codecov#L948

It is just not rendering nicely. :/

**Comment by thomasrockhu** [comment]
@jayvdb, if this is still an issue, can you open a ticket in our [community boards](https://community.codecov.io)?
