### ISSUE TITLE
We have two env files

### ISSUE THREAD

**Issue by drazisil** [codecov/codecov-bash#285]
There is an env file in both the tests dir and the repo root. Are both needed? If not, which one is used?

**Comment by TriplEight** [comment]
By default, it looks for one in project's root.
You can specify which one to use with `-y path/to/codecov.yml` with an upload script.
For example:
`bash <(curl -s https://codecov.io/bash) -y scripts/codecov.yml -f lcov.json`

**Comment by drazisil** [comment]
@thomasrockhu Did you figure this out?

**Comment by thomasrockhu** [comment]
These are not the same `env` files. The one in `tests` is used for the tests, while the one in root is used by users running Codecov inside a Docker container
