### ISSUE TITLE
Azure Pipelines token-less integration not working

### ISSUE THREAD

**Issue by jackgerrits** [codecov/codecov-bash#287]
I am trying to use CodeCov with Azure Devops Pipelines and I am not able to get the tokenless authentication working. 

When I run the bash uploader I get the following error:

https://dev.azure.com/vowpalwabbit/Vowpal%20Wabbit/_build/results?buildId=7919&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=9c939e41-62c2-5605-5e05-fc3554afc9f5&l=27177 
```sh
==> Uploading reports
    url: https://codecov.io
    query: branch=merge&commit=4c0ba2d79c63569605e85e5e12bf2ff7c9cadc47&build=20200404.18&build_url=https%3A%2F%2Fdev.azure.com%2Fvowpalwabbit%2FVowpal%20Wabbit%2F_build%2Fresults%3FbuildId%3D7919&name=&tag=&slug=VowpalWabbit%2Fvowpal_wabbit&service=azure_pipelines&flags=&pr=2385&job=7919&project=VowpalWabbit&server_uri=https://dev.azure.com/vowpalwabbit/
    -> Pinging Codecov
https://codecov.io/upload/v4?package=bash-tbd&token=secret&branch=merge&commit=4c0ba2d79c63569605e85e5e12bf2ff7c9cadc47&build=20200404.18&build_url=https%3A%2F%2Fdev.azure.com%2Fvowpalwabbit%2FVowpal%20Wabbit%2F_build%2Fresults%3FbuildId%3D7919&name=&tag=&slug=VowpalWabbit%2Fvowpal_wabbit&service=azure_pipelines&flags=&pr=2385&job=7919&project=VowpalWabbit&server_uri=https://dev.azure.com/vowpalwabbit/
HTTP 400
Unable to locate build via Azure API. Please upload with the Codecov repository upload token to resolve issue.
```

I have tried this in a PR build from a fork as well as a push triggered build on a branch on the main upstream repo.

I also tried setting CODECOV_TOKEN (which I would really like to avoid), and I get a different error:
https://dev.azure.com/vowpalwabbit/Vowpal%20Wabbit/_build/results?buildId=7952&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=9c939e41-62c2-5605-5e05-fc3554afc9f5&l=27178
```sh
==> Uploading reports
    url: https://codecov.io
    query: branch=merge&commit=89b8cb1f099e85a09d2fd298a5c2234d12f0829d&build=20200405.2&build_url=https%3A%2F%2Fdev.azure.com%2Fvowpalwabbit%2FVowpal%20Wabbit%2F_build%2Fresults%3FbuildId%3D7952&name=&tag=&slug=VowpalWabbit%2Fvowpal_wabbit&service=azure_pipelines&flags=&pr=2385&job=7952&project=VowpalWabbit&server_uri=https://dev.azure.com/vowpalwabbit/
    -> Pinging Codecov
https://codecov.io/upload/v4?package=bash-tbd&token=secret&branch=merge&commit=89b8cb1f099e85a09d2fd298a5c2234d12f0829d&build=20200405.2&build_url=https%3A%2F%2Fdev.azure.com%2Fvowpalwabbit%2FVowpal%20Wabbit%2F_build%2Fresults%3FbuildId%3D7952&name=&tag=&slug=VowpalWabbit%2Fvowpal_wabbit&service=azure_pipelines&flags=&pr=2385&job=7952&project=VowpalWabbit&server_uri=https://dev.azure.com/vowpalwabbit/
HTTP 400
Provided token is not a UUID.
```

**Comment by florimondmanca** [comment]
Also currently a bit stuck on this. Recently migrated to Azure Pipelines from Travis, used to work seamlessly there. 😕 

Example build for the first error [here](https://dev.azure.com/florimondmanca/public/_build/results?buildId=263&view=logs&j=19e19748-210f-5216-2f09-8d3e86c90a2f&t=69495144-5e18-5e1a-4cc9-dac17380db7c).

I get the second error on PRs from forks only — not on PRs I open myself. Seems like the solution would be making secrets available to forks, but I'd really like to not have to do that either.

**Comment by florimondmanca** [comment]
Just managed to make it work by specifying `-C $(Build.SourceVersion)`:

```console
bash <(curl -s https://codecov.io/bash) -C $(Build.SourceVersion)
```

Seems like Azure creates a temporary merge commit (visible in the "Checkout" step) which confuses with Codecov.

**Comment by jackgerrits** [comment]
I tried using that and I still get the same error:
> Unable to locate build via Azure API. Please upload with the Codecov repository upload token to resolve issue.

I have no visibility it seems as to what is causing it not to be found.

**Comment by mlline00** [comment]
I'm hitting the same error and, like jackgerrits, "-C $(Build.SourceVersion)" did not help.

**Comment by thomasrockhu** [comment]
Hi all, apologies for the delay in getting to this issue. However because of the age of the issue, I'm going to close out, but if it's still an issue, please open a ticket in our [community boards](https://community.codecov.io).

**Comment by abhiTronix** [comment]
Heads up everyone, `bash <(curl -s https://codecov.io/bash) -C $(Build.SourceVersion)` only works when your Azure Devope Project is **Public** and pipeline belongs it. If is already Private, just delete/disable it and make a Public one. Hope it helps.
