### ISSUE TITLE
How to avoid using an online script?

### ISSUE THREAD

**Issue by TriplEight** [codecov/codecov-bash#296]
It looks very insecure to `bash <something from the internet>` straight inside of CI.

Is there a good and sustainable way to avoid it? Clearly I can provide codecov.io with all info needed with my own script.

**Comment by thomasrockhu** [comment]
You could download this script and check the `CHECKSUM`s provided. As it is open-source, you are welcome to use it to upload coverage reports. We would, unfortunately, not be able to support edited scripts.
