### ISSUE TITLE
Upload fail when commit messages contain `merge ... into`

### ISSUE THREAD

**Issue by suguru** [codecov/codecov-bash#30]
I am using bash script to upload coverage report with command `bash <(curl -s https://codecov.io/bash)` from CircleCI.

It seems uploading tasks are always fail when commit comment is like `Merge branch 'feature' of github.com:suguru/repository into master`.

Our logs show that something happened in commit parameter.

```
(query) branch=debug-test&commit=branch&build=1871.0&build_url=&tag=&slug=suguru/repository&yaml=&service=circleci&flags=&pr=&job=
==> Uploading reports
    Pinging Codecov
    Uploading to S3

bash <(curl -s https://codecov.io/bash) returned exit code 6
```

**Comment by stevepeak** [comment]
Hey @suguru this should be fixed up by recent releases. Have you seen this issue in the past week or longer?
