### ISSUE TITLE
allow .codecov.yml (hidden file)

### ISSUE THREAD

**Issue by nschloe** [codecov/codecov-bash#303]
Basically all code meta tool config files are hidden or exist in a hidden variant, e.g.,
```
.git
.github
.circleci
.flake8
.isort.cfg
.bandit
```
It'd be lovely if codecov would allow the config to be in `.codecov.yml`, too.

**Comment by thomasrockhu** [comment]
Hi @nschloe this is now possible. I'll make a PR to update the documentation in this repo

**Comment by nschloe** [comment]
Great, thanks!
