### ISSUE TITLE
Busybox find doesn't support -execdir

### ISSUE THREAD

**Issue by danmx** [codecov/codecov-bash#304]
[Drone CI](https://drone.io) is using Busybox as their base image for their plugins, including codecov plugin.

Busybox's `find` doesn't support `-execdir` flag which prevents use of `codecov.yml` config file.
An example flag usage: https://github.com/danmx/codecov-bash/blob/49bb153/codecov#L1081-L1083

Related issue https://github.com/drone-plugins/drone-codecov/issues/17

**Comment by agboom** [comment]
Might be related to https://github.com/codecov/codecov-python/issues/243?

**Comment by thomasrockhu** [comment]
Should be fixed via https://github.com/codecov/codecov-bash/commit/fe0c473257c372daf1324bd92028c5623d1421ec#diff-45b1150df0237fb1cb2a238a2d04554e
