### ISSUE TITLE
Provided token is not a UUID error with Gitlab CI

### ISSUE THREAD

**Issue by kashyapm94** [codecov/codecov-bash#305]
I am trying to do code coverage for a flask app in Python and uploading it on the `codecov.io` platform. I am trying to upload it directly via Gitlab CI, but it doesn't happen. It keeps throwing the following error:

    HTTP 400
    Provided token is not a UUID.

I created an account on `codecov.io` and connected it to my gitlab account and selected a repository to work with. I added the token as an environment variable in gitlab CI

[![enter image description here][1]][1]

My CI file is:

    image: ubuntu:18.04

    variables:
        CODECOV_TOKEN: $CODECOV_TOKEN

    stages:
        - coverage
        - deploy

    coverage:
        stage: coverage
        before_script:
            - apt-get -y update
            - apt-get -y install curl python3-pip python3.7 zip
            - python3.7 -m pip install --upgrade pip
            - python3.7 -V
            - pip3.7 install -r requirements.txt

        script:
            - coverage run -m pytest
            - coverage report -m

        after_script:
           - bash <(curl -s https://codecov.io/bash) -t $CODECOV_TOKEN

The error screenshot:

[![enter image description here][2]][2]

But, when I did `bash <(curl -s https://codecov.io/bash) -t <token>` from the linux terminal, it was successfully uploaded.

What is the mistake that I am doing?

  [1]: https://i.stack.imgur.com/7etN4.png
  [2]: https://i.stack.imgur.com/Vv7N9.png

**Comment by thomasrockhu** [comment]
Hmmm, @kashyapm94, would you be able to add a step in your CI pipeline to `echo $CODECOV_TOKEN`? I'm wondering if it's just not getting set properly

**Comment by drazisil** [comment]
Another thing you can try, if you have the env set, you don't need the `-t $CODECOV_TOKEN` part, it will get detected automatically.

**Comment by kashyapm94** [comment]
@thomasrockhu 

![Screenshot from 2020-06-05 17-44-41](https://user-images.githubusercontent.com/35066641/83896331-441c0580-a754-11ea-933e-4274c87b2185.png)

**Comment by thomasrockhu** [comment]
@kashyapm94 looks like it's not getting set properly then? I would try @drazisil's comment

**Comment by kashyapm94** [comment]
You were right @drazisil. The protect was on. Thank you so much. It solved the issue :)
