### ISSUE TITLE
server certificate verification failed

### ISSUE THREAD

**Issue by nelsonic** [codecov/codecov-bash#309]
Greetings Codecoverers! 👋 ☀️ 

When attempting to use the bash command:

```sh
bash <(curl -s https://codecov.io/bash)
```
As per the docs: https://docs.codecov.io/docs/about-the-codecov-bash-uploader
Seeing the following error:

```sh
curl: (60) server certificate verification failed. 
CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none
More details here: http://curl.haxx.se/docs/sslcerts.html
curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.
```

See: https://travis-ci.org/github/dwyl/ping/builds/692921771#L339
![image](https://user-images.githubusercontent.com/194400/83333645-7da6c980-a299-11ea-921a-b101ba145876.png)

This is similar to https://github.com/codecov/codecov-bash/issues/128 but distinct error message hence new issue.
I will attempt to re-run the build to see if it's a Travic-CI issue.

**Comment by drazisil** [comment]
Hi @nelsonic 

Thank you for letting us know. See https://status.codecov.io/incidents/0jn3p9dx9pkq for updates, I'll close this issue since it's not a bash issue.

**Comment by nelsonic** [comment]
Hi @drazisil thanks for the prompt reply. 👍 

Given that the issue will be seen by other people using the `bash` script 
(_which is failing silently so it's definitely an issue ..._),
would it not make sense to keep the GitHub issue _open_ until it is resolved 
so that other people can avoid opening a duplicate issue? 💭 

I signed up to receive updates on the issue on the link you shared: (_thanks_)
![image](https://user-images.githubusercontent.com/194400/83335807-37586700-a2a7-11ea-8346-5b1af7184540.png)
![image](https://user-images.githubusercontent.com/194400/83335869-87372e00-a2a7-11ea-884b-8c0c1b90a2ff.png)

But I would _much_ rather just get a GitHub notification when it's resolved than have to double-opt-in to an email notification. 😕 
Totally understand/respect that Statuspage is how Codecov track incidents/issues _internally_,
but GitHub issues & notifications are a _lot_ easier to track than email (I get a lot of emails...) 📬 

Anyway, thanks for investigating. 👍 
And thanks again for a great product. ❤️

**Comment by drazisil** [comment]
@nelsonic Sure, I'll keep it open. All updates will be to the status page though.

**Comment by hootener** [comment]
@nelsonic I'm closing this issue as we've resolved it on our end. Thank you for your thoughtful issue and follow up.

**Comment by nelsonic** [comment]
@drazisil + @hootener thanks for informing that it's fixed and closing the issue. 👍 

Confirmed working in latest build: 
https://travis-ci.org/github/dwyl/ping/jobs/692968323#L387
![image](https://user-images.githubusercontent.com/194400/83339110-5dd7cb80-a2c2-11ea-9b26-493e48fed1df.png)

# 🙌
