### ISSUE TITLE
coverage in virtualenv results in .coverage not being found

### ISSUE THREAD

**Issue by tulioz** [codecov/codecov-bash#31]
When you run `coverage` from a virtual environment the bash script skips the `.coverage` file since `which coverage` doesn't return a valid path.

**Comment by stevepeak** [comment]
@tulioz Since the command `coverage` is not found how can we call `coverage xml`?

Maybe this would work:

```
# from venv
coverage xml
# from travis
bash <(curl -s https://codecov.io/bash)
```

**Comment by tulioz** [comment]
Thanks @stevepeak was a misunderstanding on my part, I thought codecov was ingesting the .coverage file not a coverage.xml file. Indeed fixed this by running `coverage xml` prior to uploading.
