### ISSUE TITLE
400 error

### ISSUE THREAD

**Issue by piotr-s-brainhub** [codecov/codecov-bash#316]
I get a 400 error in this build https://app.circleci.com/pipelines/github/brainhubeu/issue-overseer/88/workflows/f3d168d6-981d-47ef-aea4-92505d68c386/jobs/187 though locally it works with the same token. No report is uploaded. However, the exit code is 0.

**Comment by thomasrockhu** [comment]
Based on more recent [builds](https://app.circleci.com/pipelines/github/brainhubeu/issue-overseer/148/workflows/13b44c55-7dcf-4ca7-a4d6-4e795e37d02a/jobs/267), this has been fixed for you.
