### ISSUE TITLE
curl arguments set with -U are not passed to curl

### ISSUE THREAD

**Issue by mmcgr** [codecov/codecov-bash#321]
#313 seems to have broken passing arguments to curl. The curl arguments are now quoted, which means curl interprets the arguments as a single string:
https://github.com/codecov/codecov-bash/blob/40cebbd97b564cdf6577b617f42fe8109bc92c13/codecov#L1673

`codecov -U "--proxy http://http-proxy"` thus leads to `curl "--proxy http://http-proxy"`, which is not a valid argument.

**Comment by thomasrockhu** [comment]
This has been fixed via https://github.com/codecov/codecov-bash/commit/799aefe6a793dcc60e5cdda5d2c9da8b8ff2e640
