### ISSUE TITLE
swiftcov() exiting with no such file or directory since release -> 20200622-40cebbd

### ISSUE THREAD

**Issue by edwardbeecroft** [codecov/codecov-bash#322]
Hi team,

Changes to `swiftcov()` method released with `20200622-40cebbd` seem to be causing issues for our bash uploader (which is invoked as part of a job within our CircleCI workflows, during the deployment process for our iOS app), and I was hoping you could advise.

In the job, we are calling `bash <(curl -s https://codecov.io/bash) -t {token} -J '{appname}'`

For a long time this has not presented issues, but since `20200622-40cebbd` we have started seeing exits with the following output:

```
==> Circle CI detected.
    project root: .
    Yaml found at: codecov.yml
==> Processing Xcode reports via llvm-cov
    DerivedData folder: /Users/distiller/Library/Developer/Xcode/DerivedData
    + Building reports for {appName} app
/dev/fd/63: line 220: {company}/g{appName}.app.coverage.txt: No such file or directory
    x> llvm-cov failed to produce results for /Users/distiller/Library/Developer/Xcode/DerivedData/{app}/Build/Products/Dev-iphonesimulator/{appName}.app/{appName}
    -> Running gcov for Obj-C
==> Running gcov in . (disable via -X gcov)
==> Python coveragepy not found
==> Searching for coverage reports in:
    + .
    + /tmp/circleci-artifacts
    + /tmp/circleci-test-reports
--> No coverage report found.
    Please visit http://docs.codecov.io/docs/supported-languages
 ```

What seems most unusual, is this line: `line 220: {company}/g{appName}.app.coverage.txt: No such file or directory`. Specifically, the fact that `/g{appName}` is not `/{appName}`.

Prior to `20200622-40cebbd`, this job would succeed, later printing the line: `Reading reports + ./{appName}.app.coverage.txt bytes=3904639`, (i.e. with no `/g` in the path).

It seems like this change could be a potential cause. Also, $beta_xcode_partials is now wrapped in quotes, which might need review.

_Before:_

<img width="1649" alt="swiftcov-before" src="https://user-images.githubusercontent.com/44893939/85716072-01f73b80-b6e4-11ea-8920-bb485ecc6839.png">

_After:_

<img width="1632" alt="swiftcov-after" src="https://user-images.githubusercontent.com/44893939/85716102-0c193a00-b6e4-11ea-98c1-2764802278c9.png">

Thanks in advance for your help,

Ed

**Comment by JosephDuffy** [comment]
I am seeing a similar issue when using https://github.com/codecov/codecov-action.

https://github.com/JosephDuffy/GatheredKit/runs/800364486?check_suite_focus=true was working, but it has since been failing, e.g. https://github.com/JosephDuffy/GatheredKit/runs/808596736?check_suite_focus=true

**Comment by thomasrockhu** [comment]
Hi @edwardbeecroft, we have made a fix [here](https://github.com/codecov/codecov-bash/pull/323) and will be deploying shortly.

As a workaround, you can use `bash <(curl https://codecov.io/bash | sed 's/"$beta_xcode_partials"//g')` until this is deployed to production. You can also pull the bash script from this repository which has the fix and run it locally

**Comment by edwardbeecroft** [comment]
@thomasrockhu unfortunately neither the deployed change, or passing `| sed 's/"$beta_xcode_partials"//g'` as a param, fix it for us.

We still see line `220: {company}/g{appName}.app.coverage.txt: No such file or directory.`. I can't help but feel this `/g` in the path, that is not part of our app name, is causing issues?

When we download the script as it was in this release, 28 days ago, and run it locally, it works fine:

https://github.com/codecov/codecov-bash/releases/tag/20200602-f809a24

**Comment by thomasrockhu** [comment]
Hi @edwardbeecroft , would you be able to make a post in our [community boards](https://community.codecov.io) for this case? I'd like to be able to dig into why this is happening for you.

**Comment by robmaceachern** [comment]
I believe we're experiencing the same issue. There is a `/g` being inserted in our app name.

```
==> Circle CI detected.
    project root: .
    Yaml found at: codecov.yml
==> Processing Xcode reports via llvm-cov
    DerivedData folder: /Users/distiller/Library/Developer/Xcode/DerivedData
    hint Speed up Swift processing by using use -J 'AppName' (regexp accepted)
    hint This will remove Pods/ from your report. Also https://docs.codecov.io/docs/ignoring-paths
    + Building reports for Dr Bill app
/dev/fd/63: line 221: Dr/gBill.app.coverage.txt: No such file or directory
    x> llvm-cov failed to produce results for /Users/distiller/Library/Developer/Xcode/DerivedData/Dr._Bill-echlvjmpttqcmgfbphzwpighqnco/Build/Products/Debug-iphonesimulator/Dr Bill.app/Dr Bill
    
```

**Comment by robmaceachern** [comment]
@thomasrockhu I've opened a post here: https://community.codecov.io/t/bash-script-coverage-txt-file-not-found-no-such-file-or-directory/1872
