### ISSUE TITLE
Error in stopping the comment when no coverage change

### ISSUE THREAD

**Issue by Kaitou786** [codecov/codecov-bash#333]
From the [Documentation](https://docs.codecov.io/docs/pull-request-comments#requiring-changes) we've added this in our codecov.yml but still the comment is made on the PR. The comment even specify that there is no coverage change.
```
comment:
  require_changes: true
```
 Added this at the bottom of codecov.yml. We are also validating the yml. Don't know what we might me doing wrong.

PS: I'm not sure if this the right place to make this issue, if not please direct me to the right place where I might create this issue

**Comment by thomasrockhu** [comment]
HI @Kaitou786, would you be able to make an issue in the #support section of our [community boards](https://community.codecov.io)?

**Comment by Kaitou786** [comment]
@thomasrockhu thanks for the reply, I've opened this in support section in community boards, =D
