### ISSUE TITLE
Upload code coverage data from unit tests classes

### ISSUE THREAD

**Issue by eduardoeof** [codecov/codecov-bash#34]
I have a Swift project and its code coverage isn't right. I realised that codecov-bash is taking code coverage data from project's class and its unit tests. I thought it would only get class's code coverage. 

![screen shot 2016-06-25 at 21 35 48](https://cloud.githubusercontent.com/assets/1106372/16359918/e57d2b22-3b1d-11e6-9dc8-c5b68189463f.png)

**Comment by stevepeak** [comment]
Hey @eduardoeof You can specify class only via:

```
bash <(curl -s https://codecov.io/bash) -J "^Gollum$"
```

Thanks!

**Comment by eduardoeof** [comment]
Oh nice @stevepeak! I didn't know that I could use regex. Just a suggestion, the documentation could comment about regex.
