### ISSUE TITLE
Add invert match for gcov ignore switch.

### ISSUE THREAD

**Issue by ibuclaw** [codecov/codecov-bash#35]
I'm working with a frontend to a much, much larger project. However both must be built together.

After finishing the build with `--coverage` this leaves over 900 gcov files that get picked up by the codecov script. However only less than 150 of them are relevant to my project.  This results in almost 800 files being scanned, uploaded, then discarded post upload as they don't exist in the repository.

Would it be possible to add the inverse to `-g` for paths to filter for `gcov`?  Such as `-G`, which would mean that only files paths that match the given expression get scanned.

This would speed up the collection + upload times from hours to minutes.  For instance, see here where the first is 8MB, while the other is over 100MB!
https://codecov.io/gh/ibuclaw/GDC/commit/9225c1b868bbf456d19a5ac27796ec12bedc0348/builds

**Comment by stevepeak** [comment]
Hey @ibuclaw you can provide custom arguments to the gcov upload command:

> https://github.com/codecov/codecov-bash/blob/39a8cb397f8de051d3a626702e7eae71a53bc73c/codecov#L91-L96
> and https://github.com/codecov/codecov-bash/blob/39a8cb397f8de051d3a626702e7eae71a53bc73c/codecov#L654

```
bash <(curl -s https://codecov.io/bash) -a "-G..."
```

Let me know if that works out ;)

**Comment by ibuclaw** [comment]
Yeah, that's not quite right.  `-G` isn't a gcov option.  I was suggesting a potential option for the codecov bash script.

Currently you have:
```
-g GLOB      Paths to ignore during gcov gathering
```
Which translates to the following that will be passed to `find`
```
gcov_ignore="$gcov_ignore -not -path '$OPTARG'"
```
However I'd like to know if it's possible to support the opposite to `-not -path`.

**Comment by stevepeak** [comment]
Ok. I think I'm understanding this. It would help if you expressed what your command would look like in the example below.

```
# codecov command
find .-type f -name '*.gcno' -exec gcov -pb {} +
```

What would yours look like?

**Comment by ibuclaw** [comment]
Sure, it would look like this.
```
# codecov command
find .-type f -name '*.gcno' -path '*/gcc/d/*' -exec gcov -pb {} +
```

**Comment by stevepeak** [comment]
Ok, cool 👍  that makes. Does that commit above look right?

**Comment by ibuclaw** [comment]
Hey @stevepeak. Yes that looks good for my use-case, thanks!

**Comment by stevepeak** [comment]
Cool! This is deployed 👍
