### ISSUE TITLE
"Appending adjustments" takes a long time 

### ISSUE THREAD

**Issue by charleskorn** [codecov/codecov-bash#355]
I'm seeing a lot of time (~7 minutes) being spent in the "appending adjustments" step when using this with the Codecov GitHub Action. The codebase is quite small (less than 500 lines of Golang). Is this expected? 

Sample builds: https://github.com/batect/abacus/runs/1213805213?check_suite_focus=true#step:11:40 and https://github.com/batect/abacus/runs/1213735685?check_suite_focus=true#step:11:40 (compare the timestamps for line 40 with line 41).

**Comment by thomasrockhu** [comment]
@charleskorn, would you mind running this with the verbose flag (-v) and opening up a ticket in the support section of our [community boards](https://community.codecov.io)? Closing this out to handle there.
