### ISSUE TITLE
Incorrect parameter for storage.googleapis.com upload when trying to upload Xcode test result

### ISSUE THREAD

**Issue by Cyberbeni** [codecov/codecov-bash#363]
When running my tests on Linux, they upload directly to google storage: https://github.com/Cyberbeni/TypedNotificationCenter/runs/1260764308

But when running my tests on macOS, it fails every time like this:
https://github.com/Cyberbeni/TypedNotificationCenter/runs/1260764223
```
->  Uploading to
<html lang=en>
curl: (3) URL using bad/illegal format or missing URL
    X> Failed to upload
```
Then it correctly uploads to Codecov.

GitHub action workflow for the results: https://github.com/Cyberbeni/TypedNotificationCenter/blob/b7736cce7ea4103d13d5939bcf74eb465324b573/.github/workflows/run_tests.yml

**Comment by Cyberbeni** [comment]
Probably the same as #330

**Comment by thomasrockhu** [comment]
Hi @Cyberbeni, would you mind opening a ticket in the `support` section of our [community boards](https://community.codecov.io) for this?
