### ISSUE TITLE
missing required properties: ['commit'] on Travis CI

### ISSUE THREAD

**Issue by JZubero** [codecov/codecov-bash#366]
When using the Bash Uploader the recommended way for Travis CI (plain `bash <(curl -s https://codecov.io/bash)`), I am experiencing a strange problem where "Pinging Codecov" retrieves a rendered HTML error page, claiming `missing required properties: ['commit']`.

![Screenshot](https://user-images.githubusercontent.com/13751426/97778747-8a498980-1b79-11eb-8120-ce85001e7fcc.png)

The rendered HTML err page shows:

![Bildschirmfoto-20201031130155-974x463](https://user-images.githubusercontent.com/13751426/97778757-9cc3c300-1b79-11eb-8dd6-a8f04a5ed021.png)

Here is a link to the Travis CI build: https://travis-ci.com/github/Level51/silverstripe-onesignal/jobs/421697634#L633

When I am trying this within a Docker container it works with the very same command (plus the token).

**Comment by thomasrockhu** [comment]
Hi @JZubero, looks like this has been resolved as I can view the [commit page](https://codecov.io/gh/Level51/silverstripe-onesignal/commit/26f40845fc78b9065f004903534ba92ca7934da9). However, I see that we weren't able to process the report, and I think you'll need [path fixing](https://docs.codecov.io/docs/fixing-paths). Maybe

```
fixes:
  - "/home/travis/builds/ss/vendor/::"
```

in a `codecov.yml` file. If you are still experiencing issues after this, please take a look at our [troubleshooting guide](https://docs.codecov.io/docs/troubleshooting-guide) or view our [community boards](https://community.codecov.io).
