### ISSUE TITLE
https://codecov.io/bash: 502 Server Error

### ISSUE THREAD

**Issue by florimondmanca** [codecov/codecov-bash#367]
Hi! :wave:

When requesting https://codecov.io/bash, I am seeing an HTML page with a `Server Error`, rather than the actual bash script:

```
Error: Server Error
The server encountered a temporary error and could not complete your request.

Please try again in 30 seconds.
```

Started happening at least since today 11am (UTC+1). Makes my CI builds fail because my coverage script wouldn't be able to download and run the codecov bash script. Eg here's a sample of what I'm seeing on CI: 

```
$ bash <(curl -s https://codecov.io/bash)
/dev/fd/63: line 2: syntax error near unexpected token `<'
/dev/fd/63: line 2: `<html><head>'
```

I'm going to see if I can allow failures on the coverage upload job, but thought this would be of interest to other people curious about what's happening!

**Comment by thomasrockhu** [comment]
Hi, it looks like we are currently having an issue but have deployed a fix. You can read more [here](https://status.codecov.io/incidents/36hpc8mjhqql)

**Comment by florimondmanca** [comment]
Thank you! Looks like everything is back on track, thanks for responding.
