### ISSUE TITLE
Github Actions running Docker not detected

### ISSUE THREAD

**Issue by nulano** [codecov/codecov-bash#370]
Using the [first example](https://docs.codecov.io/docs/testing-with-docker#codecov-inside-docker) for Docker doesn't work on Github Actions:
```
x> No CI provider detected.
```

I believe this is due to a typo on the following line https://github.com/codecov/codecov-bash/blob/8b64f2c07d9ebc2ea2c61419009179945acbf044/env#L255

I think it should be `GITHUB_ACTIONS` instead, as that is what is used to detect it later on line https://github.com/codecov/codecov-bash/blob/8b64f2c07d9ebc2ea2c61419009179945acbf044/codecov#L797

**Comment by thomasrockhu** [comment]
@nulano, we will deploy this fix early next week
