### ISSUE TITLE
400 - Tokenless uploads are only supported for public repositories

### ISSUE THREAD

**Issue by natario1** [codecov/codecov-bash#377]
I keep getting this error lately, see for instance https://github.com/natario1/CameraView/pull/992/checks?check_run_id=1379309033 . But it used to work. The error message also includes a link to codecov docs where you clearly say that token is not needed for GitHub Actions.

**Comment by thomasrockhu** [comment]
@natario1, this is strange, as it's saying `Travis CI` is the one being detected. I'll take a look at it today.

**Comment by natario1** [comment]
Thanks @thomasrockhu . This repo was using Travis, but probably more than one year ago.

**Comment by thomasrockhu** [comment]
@natario1 is there any chance you could run this with the `-v` flag on? I'd like to see the verbose logs.

**Comment by natario1** [comment]
@thomasrockhu does this help? https://github.com/natario1/CameraView/blob/master/.github/workflows/build.yml#L10

We set TRAVIS env variable to true for historical reasons, other components depend on this value.
If this is the issue I can change it, but we always had this and codecov was working fine until a few months ago. Maybe you changed something in CI detection logic?

**Comment by thomasrockhu** [comment]
@natario1, yes, we use the `TRAVIS` env variable to signal whether or not it's running on [Travis CI](https://github.com/codecov/codecov-bash/blob/master/codecov#L511). We have been fixing up long-hanging issues with the bash uploader with detection. Given that this variable should only be set by Travis CI, I'm going to close this issue.

**Comment by natario1** [comment]
Sounds good, thanks!
