### ISSUE TITLE
Webhook fails with HTTP 400 Invalid signature

### ISSUE THREAD

**Issue by awhitford** [codecov/codecov-bash#385]
I have a [fork](https://github.com/awhitford/flutter_form_builder) of [flutter_form_builder](https://github.com/danvick/flutter_form_builder).  The project uses CodeCov, and the fork inherited a webhook for CodeCov.

However, for my fork, under _Settings / Webhooks_, the CodeCov webhook is failing.  It looks like each call is returning with
> HTTP 400 Invalid signature

I see an old issue #227, but it looks like it was resolved months ago.

I know that the Coverage report is uploaded by a Github Actions step.  As a result, what does the webhook do?  (Is it still necessary, or is it legacy that should be removed?)

**Comment by thomasrockhu** [comment]
@awhitford, please open a ticket in our [community boards](https://community.codecov.io)
