### ISSUE TITLE
suggestion: check for GITHUB_ACTIONS before DOCKER_REPO

### ISSUE THREAD

**Issue by grondo** [codecov/codecov-bash#386]
Our github workflow is set up to deploy new docker images as well as upload coverage reports, therefore we set `DOCKER_REPO` in our ci environment. This caused a strange bug where the bash uploader thought we were in a docker hub build and not a GitHub Action environment. The symptom was that the uploader requested that we manually set a token for the upload.

The w/a is easy -- unset `DOCKER_REPO` before calling the bash uploader.

However, since it is very unlikely that `GITHUB_ACTIONS` is set in the environment of a DockerHub build, but is more likely `DOCKER_REPO` would be set within a Github Action environment, testing for `GITHUB_ACTIONS` _first_ in the bash uploader might prevent other users from hitting this same issue.

Thanks!

**Comment by JossWhittle** [comment]
Thank you @grondo ! This was my error also. Very confusing to debug.
