### ISSUE TITLE
Issue detecting commit SHA

### ISSUE THREAD

**Issue by ktomk** [codecov/codecov-bash#397]
When using the Gitub Action, the log shows the following - otherwise undocumented - error message (it is in red):

~~~
->  Issue detecting commit SHA. Please run actions/checkout with fetch-depth > 1 or set to 0
~~~

(shown directly after `==> GitHub Actions detected.`).

This message is shown regardless the `fetch-depth` for the checkout action is default (`1`), `500` or unlimited (`0`). The last two settings were suggested by the error message, but did not change the behaviour.

Would it be possible to shed some more light? Could it be the reason is that the last report is ages ago on Codecov? Which limits are effective?

This is a public repository on Github.

The logs are available online:

- `1` (default): https://github.com/ktomk/n98-magerun/runs/1605844116?check_suite_focus=true#step:7:21
- `500`: https://github.com/ktomk/n98-magerun/runs/1605963666?check_suite_focus=true#step:7:21
- `0`: https://github.com/ktomk/n98-magerun/runs/1606000192?check_suite_focus=true#step:7:21

**Comment by thomasrockhu** [comment]
Hi @ktomk, thanks for this! Would you be able to run with the `verbose`(-v) flag on so we can take a look? It is likely a bug on our end.

**Comment by ktomk** [comment]
Hey @thomasrockhu, sure, results are already in: https://github.com/ktomk/n98-magerun/runs/1606114562?check_suite_focus=true#step:7:5

**Comment by ktomk** [comment]
and if mc stands for merge-commit, this is just a push (without associated Github PR if that it's looking for some merge-base or so). but me is just guessing here. [see line 110](https://github.com/ktomk/n98-magerun/runs/1606114562?check_suite_focus=true#step:7:110). logs should be available the next 90 days.

**Comment by thomasrockhu** [comment]
Awesome thanks @ktomk. The error message right now is innocuous so it shouldn't need a workaround, but it definitely is confusing for users. I'll work on a fix next week (holidays).

**Comment by ktomk** [comment]
Thanks for the very fast response/confirmation and have nice holidays.

**Comment by thomasrockhu** [comment]
@ktomk this [PR](https://github.com/codecov/codecov-bash/pull/398) should fix the issue. I expect to merge and deploy early next week.
