### ISSUE TITLE
Seeing unrelated files

### ISSUE THREAD

**Issue by mgeisler** [codecov/codecov-bash#4]
Hi there. Now that #3 is merged, I could submit my coverage report.

However, when I go to https://codecov.io/github/zerovm/swift-browser?ref=87d20ee8e010b1e9172209dc8a0e742540654a95 -- the URL printed by the `codecov` script, I see strange files I don't recognize. This is from a small AngularJS project built on Travis -- I have no idea who the "kpdecker" user could be.

**Comment by stevepeak** [comment]
Which file directories are correct? I'll look into the others.

Another option you can do is in our interface there is two Features Ignore Files and Fix Paths. Using both of them will solve your issue too. But I would like to add this the uploader so that other customers don't see this as well.

Thanks!

**Comment by mgeisler** [comment]
It's only `app/js` that I can recognize as mine. The other paths contain unrelated files.

**Comment by stevepeak** [comment]
If you could add the following test to the [Ignore Files](https://codecov.io/github/zerovm/swift-browser/features/ignore)

```
resources/app/*
Users/*
```

Hit submit and look at the report. Thanks!

**Comment by mgeisler** [comment]
Yes, that made the report look correct. However, I don't understand where the files came from in the first place. I have tried rebuilding on Travis and got the same report, so it seems to be deterministic.

I switched to the Bash upload script to avoid using `sudo` and thus be able to use the new container based builds in Travis. Do you think this could be a problem on Travis' side?

**Comment by stevepeak** [comment]
Not quite sure on that one. The file path `Users/...` throws me for a loop. I may fork the repo to inspect and find the culprit reports to skip them in the future.

**Comment by mgeisler** [comment]
The `Users/` paths makes me think that there is a Mac OS X machine involved somewhere -- which there isn't... I develop on Linux and I believe Travis ran the build on a Linux machine too.

**Comment by tabuchid** [comment]
Question about this. Can you adjust the Ignore Files via the uploader or something where we can check in the configuration instead of relying on a GUI configuration?

**Comment by stevepeak** [comment]
Indeed this is a fine idea. I'll make note of it for my next hack on the uploader. Thank you @tabuchid

**Comment by tabuchid** [comment]
There actually is a way to do this with the current script. Here is a snippet from my circle.yml to do this on a ios project.
```
test:
    override:
        - xctool
          -reporter pretty
          -reporter junit:$CIRCLE_TEST_REPORTS/xcode/results.xml
          -reporter plain:$CIRCLE_ARTIFACTS/xctool.log
          CODE_SIGNING_REQUIRED=NO
          CODE_SIGN_IDENTITY=
          PROVISIONING_PROFILE=
          GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES
          GCC_GENERATE_TEST_COVERAGE_FILES=YES
          -destination 'platform=iOS Simulator,name=iPhone 6,OS=latest'
          -sdk iphonesimulator
          -workspace $XCODE_WORKSPACE
          -scheme $XCODE_SCHEME
          build build-tests run-tests
    post:
        - bundle exec slather coverage --output-directory $CIRCLE_ARTIFACTS/coverage_reports/ && ./script/codecov -f $CIRCLE_ARTIFACTS/coverage_reports/cobertura.xml
```

**Comment by stevepeak** [comment]
Related note: If the desired ignore paths may be common to other repos I can program then into our backend to automatically ignore.

**Comment by drazisil** [comment]
Closing stale issue
