### ISSUE TITLE
Support coverage reporting in YAML files

### ISSUE THREAD

**Issue by mdboom** [codecov/codecov-bash#407]
Thanks for codecov.io!

We are attempting to use a custom coverage reporting tool to file coverage reports for YAML files.  I understand that's probably a bit of an unusual use case: we generate code from YAML files and then want to report which of the generated objects are tested in a unit test suite.

Unfortunately, it looks like YAML files are explicitly excluded from coverage reports [as of this commit](https://github.com/codecov/codecov-bash/commit/aa5f5839776e02769eac09aa02f3360799da6eae).  Would it be possible to just remove these?  If there's a good reason they should remain, maybe a flag to change this pattern would work (but be more effort)?

FYI and for more context: https://github.com/mozilla/glean/pull/1482

**Comment by thomasrockhu** [comment]
Hi @mdboom, thanks for this feature request! Would you be able to open an issue in the `feature requests` section of our [community boards](https://community.codecov.io)?
