### ISSUE TITLE
Upload fails with "Build has already finished, uploads rejected"

### ISSUE THREAD

**Issue by vfdev-5** [codecov/codecov-bash#411]
Since few days, we start seeing on one our CI the following message:
```
{'detail': ErrorDetail(string='Build has already finished, uploads rejected.', code='not_found')}
404
```
on the command: `bash <(curl -s https://codecov.io/bash) -Z -F gpu`.

We have multiple CI's running various non-overlapping tests and we upload reports with different tags. Job can end at different times and send reports within 1h.

Is it now an expected behaviour to reject uploads ? How then it is determined the end of the build such that it becomes finished ?
Thanks

**Comment by thomasrockhu** [comment]
Hi @vfdev-5, we have shipped a fix for this now. let me know if you are still running into issues

**Comment by vfdev-5** [comment]
Seems like it is better now, thanks !
