### ISSUE TITLE
[FR?] Uploading reports as archive

### ISSUE THREAD

**Issue by LebedevRI** [codecov/codecov-bash#437]
This is either a feature request, or a documentation request.
The native https://github.com/codecov/codecov-bash uploads
each report separately, which doesn't quite scale well with
large report number. I'm seeing that the upload takes
an extremely long time. It would perhaps be good to be able
to archive the reports first, and upload them in one go.

Is that something that can be done?

X-Ref https://github.com/codecov/codecov-action/issues/324

**Comment by thomasrockhu** [comment]
(closing out as a duplicate on the mentioned issue)

**Comment by LebedevRI** [comment]
... could you please bother to actually reply to the issue?

**Comment by LebedevRI** [comment]
Thank you for a very helpful reply!
The answer i was looking for: "your problem is elsewhere, we already do that: https://github.com/codecov/codecov-bash/blob/965008c97d649721850b9ff0de3f71e9b8adeb71/codecov#L1796-L1798"
