### ISSUE TITLE
CI continues despite failure to release

### ISSUE THREAD

**Issue by matthewberryman** [codecov/codecov-bash#446]
Looks like something went wrong with your releasing step, as the current published bash script doesn't match the (github) released version; an assumption that your circleci orb relies on when validating the bash script against checksums. This then breaks all my usage of codecov, which relies on the orb. 
More: https://github.com/codecov/codecov-circleci-orb/issues/92

**Comment by Tbilgere-td** [comment]
Can confirm, Checksum stopped passing for us as well on multiple environments this evening.

**Comment by matthewberryman** [comment]
Digging a bit deeper:
This line in one of your CI scripts https://github.com/codecov/codecov-bash/blob/c3ccd596467b6c08e6fba7dba6e048dd0e341421/scripts/version.sh#L26 relies on the version being updated in the bash script (it has not been in a while, despite changes) and the CircleCI ignores the git failure (not sure why yet as this exit code should be passed out as an error not 0)

**Comment by thomasrockhu** [comment]
Hi all, I have made the change on our end and deployed `1.0.4`. Please let me know if you are still experiencing the issue

**Comment by Tbilgere-td** [comment]
> Hi all, I have made the change on our end and deployed `1.0.4`. Please let me know if you are still experiencing the issue. It should be live within an hour.

Hey, just attempted a build and it appears the 1.0.4 release did not include the necessary assets as such the file at `https://codecov.io/bash` is still 1.0.3 and does not pass checksum.

**Comment by jpeach** [comment]
> > Hi all, I have made the change on our end and deployed `1.0.4`. Please let me know if you are still experiencing the issue. It should be live within an hour.
> 
> Hey, just attempted a build and it appears the file at `https://codecov.io/bash` is still 1.0.3 and still does not pass checksum. Perhaps something to do with the 1.0.4 release not including the necessary assets?

Confirmed that this is still broken. 

```
$ curl -s -L https://codecov.io/bash | grep ^VERSION=
VERSION="1.0.3"
```

Since this problem is breaking CI for projects, is there a time frame for fixing it?

**Comment by ouranos** [comment]
Yes, still broken, had the issue this morning: https://github.com/codecov/codecov-bash/issues/449

**Comment by thomasrockhu** [comment]
Hi all, I made a fix in the deployment, it should be showing `1.0.4` now.

**Comment by jpeach** [comment]
> Hi all, I made a fix in the deployment, it should be showing `1.0.4` now.

Verified that this works in our CI. Thanks @thomasrockhu :100:
