### ISSUE TITLE
"raw" upload command?

### ISSUE THREAD

**Issue by gliptak** [codecov/codecov-bash#52]
Would the "raw" upload command be available (in particular for a ```Go``` project with a ```coverage.txt``` file)? Instead of running a shell download from the internet, some project might choose to use that instead. Thanks

**Comment by stevepeak** [comment]
Hey @gliptak Yes this does indeed work for go: https://github.com/codecov/example-go

You can configure your own http post of report content to Codecov if the shell script is not desired. We are also looking into packaged options, e.g., apt-get, yum, etc.

You can also use the python package: `pip install --user codecov && codecov`.

Thanks!

**Comment by gliptak** [comment]
Thank you for the pointer. Would you have also have details on  the parameters of HTTP post (an maybe a ```wget```/```curl``` example)?

**Comment by stevepeak** [comment]
Sure :)

Here is the minimum requirements, you can discover the remaining arguments [here](https://github.com/codecov/codecov-bash/blob/master/codecov#L729-L740)

```shell
curl -X POST \
  -H 'Accept: application/json' \
  --data-binary @coverage.txt \
  "https://codecov.io/upload/v2?commit=<sha>&token=<uuid-token>"
```

**Comment by gliptak** [comment]
I came up with (public repo so no ```token``` required?):
```
curl -X POST -H 'Accept: application/json' --data-binary @coverage.txt "https://codecov.io/upload/v2?commit=$TRAVIS_COMMIT&pr=$TRAVIS_PULL_REQUEST&slug=$TRAVIS_REPO_SLUG"
```
but it throws ```No such file or directory```

Would I need additional parameters?

https://travis-ci.org/cloudflare/cloudflare-go/jobs/196191034

**Comment by stevepeak** [comment]
Hey @gliptak 

`No such file or directory` would be an issue with the file `coverage.txt` not existing.  I'm not sure what your coverage file name is, but it appears to not be `coverage.txt`. I just used that name as an example. The bash uploader can detect common files names [here](https://github.com/codecov/codecov-bash/blob/20901fe5a15f2687674bb843e16717d4dbc96e3a/codecov#L824).

There are other requirements for the "no token" feature with travis. Please check them all out [here](https://github.com/codecov/codecov-bash/blob/20901fe5a15f2687674bb843e16717d4dbc96e3a/codecov#L388-L394).

Thank you! I'm happy to help our more 👍

**Comment by gliptak** [comment]
@stevepeak Thank you for helping me with this.

https://travis-ci.org/cloudflare/cloudflare-go/jobs/196438911
```
$ ls -l coverage.txt
-rw-r--r-- 1 travis travis 23538 Jan 29 22:48 coverage.txt
$ {:"curl -X POST -H 'Accept"=>"application/json' --data-binary @coverage.txt \"https://codecov.io/upload/v2?commit=$TRAVIS_COMMIT&pr=$TRAVIS_PULL_REQUEST&slug=$TRAVIS_REPO_SLUG\""}
/home/travis/build.sh: line 57: application/json' --data-binary @coverage.txt "https://codecov.io/upload/v2?commit=79f713c3504b71309726644ee12a9c85a76ed0cb&pr=111&slug=cloudflare/cloudflare-go"}: No such file or directory
```
If the ```coverage.txt``` files exists, what other reasons might be for ```No such file or directory```?

**Comment by stevepeak** [comment]
Can you try this:

```diff
- $ {:"curl -X POST -H 'Accept"=>"application/json' --data-binary @coverage.txt \"https://codecov.io/upload/v2?commit=$TRAVIS_COMMIT&pr=$TRAVIS_PULL_REQUEST&slug=$TRAVIS_REPO_SLUG\""}
+ curl -X POST --data-binary @coverage.txt "https://codecov.io/upload/v2?commit=$TRAVIS_COMMIT&pr=$TRAVIS_PULL_REQUEST&slug=$TRAVIS_REPO_SLUG"
```

I have not used the prior technique and this `/home/travis/build.sh: line 57: application/json'` tells me something is wrong with the format.

**Comment by gliptak** [comment]
OK, an actual error, a bit confusing as we should be able to skip the token?

https://travis-ci.org/cloudflare/cloudflare-go/jobs/196470037

```
<div class="status">400</div>
<div class="reason">Please provide the repository token to upload reports via `-t :repository-token`</div>
```

**Comment by stevepeak** [comment]
This would be from the lack of Travis variables provided. I should have included them in the full request. So here we go 😄 

```
curl -X POST --data-binary @coverage.txt "https://codecov.io/upload/v2?commit=$TRAVIS_COMMIT&pr=$TRAVIS_PULL_REQUEST&slug=$TRAVIS_REPO_SLUG&job=$TRAVIS_JOB_ID&build=$TRAVIS_JOB_NUMBER&branch=$TRAVIS_BRANCH"
```
> Note the addition of `job` and `build` arguments.

**Comment by gliptak** [comment]
Still wants the token ...

https://travis-ci.org/cloudflare/cloudflare-go/jobs/196819806#L354

```
<div class="status">400</div>
<div class="reason">Please provide the repository token to upload reports via `-t :repository-token`</div>
```
