### ISSUE TITLE
Not possible to process multiple .coverage files

### ISSUE THREAD

**Issue by hugoduncan** [codecov/codecov-bash#53]
I'm trying to upload multiple `.coverage` files using the bash uploader.

I have tried specifying `-s` to specify the location of each file, but this does not work, as the uploader always does a search from `$git_root`, and always finds the first file.

**Comment by stevepeak** [comment]
Hey @hugoduncan how is your project structured? Where are these `.coverage` files located?

*If I may guess* You may need to call `coverage xml` on your own in each folder

```shell
cd project_a && coverage xml && mv coverage.xml ../project_a.coverage.xml
cd ../
cd project_b && coverage xml && mv coverage.xml ../project_b.coverage.xml

bash <(curl -s https://codecov.io/bash) -f ../project_a.coverage.xml -F project_a
bash <(curl -s https://codecov.io/bash) -f ../project_b.coverage.xml -F project_b
```

**Comment by hugoduncan** [comment]
Thanks, a variant of that works nicely.
