### ISSUE TITLE
testing-with-docker: https://codecov.io/env returns access denied

### ISSUE THREAD

**Issue by jcfr** [codecov/codecov-bash#57]
Dear Project maintainer, 

Thanks again for providing such a neat infrastructure for managing code coverage :+1: 

That said, trying to download the `env` script using https://codecov.io/env (as explained in the [testing-with-docker](https://docs.codecov.io/docs/testing-with-docker) documentation) fails with the following response:

```html
<!DOCTYPE html>
	<html>
	  <head>
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<meta charset="utf-8">
		<title>Application Error</title>
		<style media="screen">
		  html,body,iframe {
			margin: 0;
			padding: 0;
		  }
		  html,body {
			height: 100%;
			overflow: hidden;
		  }
		  iframe {
			width: 100%;
			height: 100%;
			border: 0;
		  }
		</style>
	  </head>
	  <body>
		<iframe src="https://d234q63orb21db.cloudfront.net/cd118a714294f80d079e8514f43792f519841d20/media/html/error.html"></iframe>
	  </body>
	</html>
```

When you have a chance, could you have a look ? 

Merci

Cc: @thewtex

**Comment by stevepeak** [comment]
We have a fix in the pipe for this. Very sorry about the issue. Should be release by tonight.

**Comment by jcfr** [comment]
Outstanding. Looking forward to it. And thanks for the quick reply :+1:

**Comment by stevepeak** [comment]
Deployed! Thank you for your patience.

**Comment by jcfr** [comment]
Thanks @stevepeak 

I confirm that the file is now available :+1:
