### ISSUE TITLE
Support CircleCI 2.0

### ISSUE THREAD

**Issue by dtinth** [codecov/codecov-bash#58]
[CircleCI 2.0](https://circleci.com/blog/say-hello-to-circleci-2-0/), currently in closed beta, supports Docker out-of-the-box. It brings [a lot of nice improvements](https://discuss.circleci.com/t/circleci-2-0-overview/8086).

However, [there are changes in environment variables](https://discuss.circleci.com/t/circleci-environment-variables-1-0-vs-2-0/9584). The variables `CIRCLE_PROJECT_USERNAME` and `CIRCLE_PROJECT_REPONAME` has been removed.

I have added support in Node version here: https://github.com/codecov/codecov-node/pull/46

I am not that familiar with bash scripting, I will leave this as an issue. Thanks!

**Comment by stevepeak** [comment]
Thank you @dtinth I'll use your node pull to update the bash uploader.
