### ISSUE TITLE
Recent commits broke it

### ISSUE THREAD

**Issue by rsyring** [codecov/codecov-bash#59]
Sorry I don't have a better title.  :)

```
bash <(curl -s https://codecov.io/bash) -X coveragepy -t <token>

/dev/fd/63: line 1: syntax error near unexpected token `newline'
/dev/fd/63: line 1: `<!DOCTYPE html>'

bash <(curl -s https://codecov.io/bash) -X coveragepy -t <token>
 returned exit code 2

Action failed: bash <(curl -s https://codecov.io/bash) -X coveragepy -t <token>
```

The output above was from output on Circle CI.  Jobs were otherwise working well today, the error just started showing up in the last few hours.

**Comment by stevepeak** [comment]
We had some server errors that occurred during this time. I suspect that was the issue.

Can you confirm it's working again? Thank you,
Steve

**Comment by rsyring** [comment]
Yes, it is, thanks.

**Comment by LukeTrynchuk** [comment]
I too can confirm this same issue has occurred for me.
