### ISSUE TITLE
Please add license header

### ISSUE THREAD

**Issue by hartwork** [codecov/codecov-bash#63]
Hi!

Without a license header in [codecov](https://github.com/codecov/codecov-bash/blob/master/codecov) I need to assume "all rights reserved" for a license. Is that true? Please add a license header stating what the license is. Thank you!

Best, Sebastian

**Comment by jayvdb** [comment]
A license header was added in https://github.com/codecov/codecov-bash/commit/1a5e41a27687becd428706162f2a4035b52285bf

**Comment by hartwork** [comment]
Thank you!

**Comment by jayvdb** [comment]
@drazisil I think this can be closed.
