### ISSUE TITLE
Add support for Jenkins Blue Ocean

### ISSUE THREAD

**Issue by rochdev** [codecov/codecov-bash#66]
See codecov/codecov-node/issues/55

**Comment by stevepeak** [comment]
This change should do the trick: https://github.com/codecov/codecov-bash/blob/a7792cd49f92cd359d789cc0aa576d1e562bac49/codecov#L410

The `git log -1 --format="%H"` is built into the bash uploader already.

Look good to you?

**Comment by rochdev** [comment]
@stevepeak This change includes Groovy syntax which is invalid bash (see failing tests). Also, it doesn't take the `CHANGE_ID` for the pull request and it might result in an empty URL in some cases.

**Comment by stevepeak** [comment]
Thank you! Adding now and deploying soon.
