### ISSUE TITLE
Last version breaks Jenkins pipeline (not multibranch) 

### ISSUE THREAD

**Issue by sebastienvas** [codecov/codecov-bash#68]
[mixer] Running shell script
+ curl -s https://codecov.io/bash
+ bash /dev/stdin -K

  _____          _
 / ____|        | |
| |     ___   __| | ___  ___ _____   __
| |    / _ \ / _` |/ _ \/ __/ _ \ \ / /
| |___| (_) | (_| |  __/ (_| (_) \ V /
 \_____\___/ \__,_|\___|\___\___/ \_/
                              Bash-e4a745b

==> Jenkins CI detected.

And then nothing else. After some investigation I think the issue is in here
https://github.com/codecov/codecov-bash/blob/e4a745b/codecov#L416

I also find it really weird that the script still checks for CI even though I am passing in the arguments.

The last working version for us is:
https://github.com/codecov/codecov-bash/blob/d642346/codecov#L406

**Comment by ypconstante** [comment]
I started to use Codecov today and had this same problem.
The version in commit d642346 also solved the problem for me.

**Comment by sebastienvas** [comment]
I ended up changing my pipeline libraries to set GIT_COMMIT and GIT_BRANCH when checking out the code. More details at https://github.com/istio/istio-testing/commit/96c1bdb12710c3aea44fb0a2242203bcb8ccf70e

**Comment by stevepeak** [comment]
Thank you for reporting. Do you have a suggestion on how to resolve this?

**Comment by sebastienvas** [comment]
One of the issues is that CI detection is happening regardless of argument passed in. Since I passed in arguments I did not expect CI detection to fail.

The second issues would be to update 
https://github.com/codecov/codecov-bash/blob/master/codecov#L418
from : 
 [ ! -z "$BRANCH_NAME" ] && echo "$BRANCH_NAME")
to
 || echo "$BRANCH_NAME")
as it is done in here:
https://github.com/codecov/codecov-bash/blob/master/codecov#L420 for GIT_COMMIT

**Comment by richistron** [comment]
I'm having the same problem

**Comment by thomasrockhu** [comment]
Is this still an issue @sebastienvas @richistron?

**Comment by sebastienvas** [comment]
Haven't used codecov and jenkins in a while. Probably outdated.
