### ISSUE TITLE
Generated emails are reported as spam by Inbox

### ISSUE THREAD

**Issue by TimvdLippe** [codecov/codecov-bash#69]
Recently, all CodeCov GitHub emails are automatically flagged as spam by Google Inbox. Maybe an email setting is wrong and now incorrectly flagging this service as spam?

**Comment by stevepeak** [comment]
Codecov does not send out emails. The emails are submitted by GitHub. I do not know what help I can provide here.

**Comment by TimvdLippe** [comment]
I am not sure what exactly is flagging the CodeCov e-mails, but all my other GitHub e-mails are working just fine. Maybe have to contact GitHub or Google?

**Comment by stevepeak** [comment]
Maybe you blocked the @codecov-io bot?

https://cl.ly/1w3C390U091C

**Comment by TimvdLippe** [comment]
@stevepeak No, I have not.

**Comment by TimvdLippe** [comment]
It seems that this issue has been resolved since. They are no longer marked as spam 🎉
