### ISSUE TITLE
codecov seems to handle branch data in incorrect way

### ISSUE THREAD

**Issue by lplewa** [codecov/codecov-bash#74]
example raport:
https://codecov.io/gh/lplewa/codecov_tests/src/7483e6bc6f4b96525eef5657370cae84e7bf8791/foo.c#L15

In the raport above, if in line 15 is "yellow" , but all his branches are green, what looks like the bug.
if we will check a uploaded raport we can find 4 branches where there should be only two
```
   2:   15:	if (c == 0) {
 branch  0 taken 100% (fallthrough)
 branch  1 taken 0%
 branch  2 taken 0% (fallthrough)
 branch  3 taken 100%
         1:   16:		ret += 4;
         -:   17:	} else {
         1:   18:		ret += 8;
         -:   19:	}
```
it happened because i compiled this code two times (with two separate binaries) - so i have two separate gcda//gcno files per one source file. When you call gcov command on this two gcda at once 
we will get one gcov file with branch data merged in way showed above (imo it might be gcov bug)

anyway i did a try to generate manually gcov files to get separate file per gcda//gcno file

a result this experiment you can find here: https://codecov.io/gh/lplewa/codecov_tests/src/c5c2ca0746b3a3829711a0370c6a8b07764e5ce6/foo.c#L15

now there is two gcov files
first:
```
        1:   15:	if (c == 0) {
branch  0 taken 100% (fallthrough)
branch  1 taken 0%
        1:   16:		ret += 4;
        -:   17:	} else {
    #####:   18:		ret += 8;
        -:   19:	}
```
second:
```
        1:   15:	if (c == 0) {
branch  0 taken 0% (fallthrough)
branch  1 taken 100%
    #####:   16:		ret += 4;
        -:   17:	} else {
        1:   18:		ret += 8;
        -:   19:	}
```

in my opinion in this case "if" should be green, but is still yellow, so it's seems that codecov didn't properly merged branching data.

also i did a test when i uploaded two separate raports - first for tests witch covers first branch, second raport for tests with covers second branch. Unfortunately if is still "yellow"
https://codecov.io/gh/lplewa/codecov_tests/src/ab9474598cd5af066227542962b205dd3cc5e9e4/foo.c

Can you fix merging branch data and add to codecov-bash script option to call gcov per gcda file (with -l flag to protect from file name conflict) instead of calling gcov for all gcda files at once.

**Comment by thomasrockhu** [comment]
@lplewa, this is a fairly old ticket. If this is still an issue, please open up a ticket in our [community boards](https://community.codecov.io).
