### ISSUE TITLE
Travis CI just says "No coverage report found"

### ISSUE THREAD

**Issue by LuCavallin** [codecov/codecov-bash#78]
`language: go

go:
  - 1.8.x
before_script:
  - go get ./...
  - go vet ./...
after_success:
  - bash <(curl -s https://codecov.io/bash)
`

This is my conf file. Nothing happens - I think it should be plug-n-play, but it's not :(

**Comment by stevepeak** [comment]
Can you please make sure a coverage file is created before uploading to Codecov. There should be a `coverage.txt` file created.

https://github.com/codecov/example-go

Thank you,
Steve
