### ISSUE TITLE
[ "$(which coverage)" != "coverage not found" ]

### ISSUE THREAD

**Issue by zbeekman** [codecov/codecov-bash#8]
I suspect this is the culprit of an error I’m seeing, but I’m not 100% sure. The error is here: https://travis-ci.org/zbeekman/json-fortran/jobs/66252248#L1519 which in turn implicates https://github.com/codecov/codecov-bash/blob/master/codecov#L328 But, L328 should not cause a problem if an executable named `coverage` exists, and this is checked for in [line 321](https://github.com/codecov/codecov-bash/blob/master/codecov#L321) which leads me to suspect that this test is incorrectly thinking that the coverage program is present when it is not.

Why not just test the return status of the `which` command? It seems fragile to test against a specific output string. I think this would be more robust:

```bash
if which coverage >/dev/null 2>&1; then
  …
else
  …
fi
```

From the man page:

> Which returns the number of failed arguments, or -1 when no `programname´ was given.

**Comment by stevepeak** [comment]
Thanks for finding this. Odd how this has not presented an issue before. But I'll make sure it is fixed up.

**Comment by zbeekman** [comment]
well it doesn’t cause the build to fail AFAICT it just causes an error message. And it was only introduced 13 days ago in a5c25b53ab5e44b1b6acfabbd657c33914ba6d19. The only reason I found it was that I was looking for something else in the travis logs and spotted it.

**Comment by stevepeak** [comment]
Thanks for following up. I believe that commit should do the trick to hush that error.

**Comment by zbeekman** [comment]
OK, great. I’m not sure how to test it until it’s the default code fetched
with the curl command in the documentation. Just curious why not just use
the exit status of `which` rather than parsing its output?

**Comment by stevepeak** [comment]
This is where my bash knowledge is challenged. How would I write that line more efficiently?

```sh
if [ "$(which coverage >/dev/null 2>&1 | tr '\/' '\n' | tail -1)" = "coverage" ];
```

**Comment by zbeekman** [comment]
First of all the expression you have above will always be false since you are piping stderr into stdout `2>&1` and piping stdout into `/dev/null`. In your shell try this `which ls >/dev/null 2>&1` and this `which fake_command >/dev/null 2>&1`. Neither will create any output since we’re throwing any output away. However, if you type `echo $?` after each command, you should get `0` (success/true) for the first and something non-zero (failure/false) for the second command, since `ls` is a command on your path and `fake_command` is not.

Check this out to for reference: http://tldp.org/LDP/abs/html/testconstructs.html

> An if/then construct tests whether the exit status of a list of commands is 0 (since 0 means “success" by UNIX convention), and if so, executes one or more commands.

So in your `if` construct, the command that is being run is the `[` command which is [a built in synonym](http://tldp.org/LDP/abs/html/testconstructs.html#TTESTREF) for the `test` command. The `if` statement then looks at the exit status of this test command to determine whether to take the `true` branch or the `false` (else) branch. By parsing the output of which and performing a string comparison in the test command, you are  making your life much more difficult than it needs to be: You can simply use the return value of `which coverage` to determine if one or more or more versions of `coverage` are available:

```bash
if which coverage >/dev/null 2>&1; then
  # do things using coverage because it’s here and on the PATH
else
  # code to run if `coverage` executable not found
fi
```

This solution is clearer, more concise, more robust, and probably faster. Any way, there’s always more than one way to skin a cat, but generally parsing output of commands should be avoided if you can just use the commands exit status. And you probably want to get rid of the redirection of stdout and stderr in your version of the code, because if you keep them, you’ll just be parsing the null string and the true branch will never be taken.

**Comment by zbeekman** [comment]
hit the wrong button, sorry. Please see above

**Comment by zbeekman** [comment]
https://github.com/codecov/codecov-bash/blob/f90ea4e266b373d56eb450a8f3fd857c07f7c1c5/codecov#L361 looks good to me… I haven’t tested it feel like we can probably close this issue if you are satisfied… it looks like it should work to me.

**Comment by stevepeak** [comment]
Great! The master branch is looking nice. Would you have a change to give it a spin?

Currently production version is https://github.com/codecov/codecov-bash/commit/e0866065a0489f4649d365bf5e23fb1d3e838b6a

**Comment by zbeekman** [comment]
no promises, but I’ll try to give it a shot tonight or later this weekend.

**Comment by stevepeak** [comment]
This should all be working now. Thank you for your help @zbeekman :+1:
