### ISSUE TITLE
Warn if git is missing

### ISSUE THREAD

**Issue by lazka** [codecov/codecov-bash#84]
Using the bash script in docker fails to get the config because by default most docker images don't have git installed.

I figured it out eventually, but a warning/error would have been nice.

**Comment by stevepeak** [comment]
@lazka We have another technique where you export the report(s) out of docker and upload them with `git` as a command. See here: https://docs.codecov.io/docs/testing-with-docker

**Comment by Midnighter** [comment]
Still, on that very page a warning that the technique *inside* requires git would have saved us quite a bit of trouble.

**Comment by rgov** [comment]
I was going to file the same bug for `curl`. Is there a list of all the tools that the script relies on that are not, say, included in a base Debian image? Can these all be tested for by the script?

**Comment by thomasrockhu** [comment]
Fixed via https://github.com/codecov/codecov-bash/pull/394
