### ISSUE TITLE
Wrong version advertised in https://codecov.io/bash

### ISSUE THREAD

**Issue by adiroiban** [codecov/codecov-bash#90]
The file which is now at https://codecov.io/bash has `VERSION="d109cc7"`

I have a version cached 10 days ago, which has the same  version, but is different to the "latest" on.

Here is the diff.

I think that the version on https://codecov.io/bash should have a different VERSION

```
diff --git a/tools/codecov.sh b/tools/codecov.sh
index f47caf7..4021502 100755
--- a/tools/codecov.sh
+++ b/tools/codecov.sh
@@ -1207,6 +1207,15 @@ do
   fi
 done <<< "$(echo -e "$files")"
 
+if [[ $(find $upload_file -type f -size +104857600c 2>/dev/null) ]]; then
+  say "${r}-->${x} Sorry, the resulting file is to large for uploading."
+  say "    We are working on a solution for large files and will remove this message"
+  say "    when we have resolved the issue. Thank you for your patience."
+  say "    Max upload size is 100mb."
+  curl https://codecov.io/log?$query 2>/dev/null >/dev/null
+  exit ${exit_with};
+fi
+
 if [ "$fr" = "0" ];
 then
   say "${r}-->${x} No coverage data found."
```

**Comment by stevepeak** [comment]
@adiroiban Thank you for pointing this out. We made a quick patch to the script in order to remove these large files. Future versions will support them.

**Comment by darioizzo** [comment]
The patch is actually breaking our coverage build "https://travis-ci.org/esa/pagmo2/jobs/286527538". Any workaround to implement? When is the support to large files being restored?

**Comment by darioizzo** [comment]
@stevepeak Any progress on this? I would like to know if support for large files will be restored any time soon as our CI is consistently breaking now. I can remove the code coverage from the builds of course, but I would rather have it
