### ISSUE TITLE
Failing on busybox 1.26, incorrect flags passed to `find`

### ISSUE THREAD

**Issue by dnephin** [codecov/codecov-bash#91]
See: https://circleci.com/gh/riyazdf/cli/1900 (last step "Upload to Codecov")

```
==> Circle CI detected.
    project root: .
    Yaml found at: codecov.yml
==> Running gcov in . (disable via -X gcov)
==> Python coveragepy not found
==> Searching for coverage reports in:
    + .
    -> Found 1 reports
==> Detecting git/mercurial file structure
==> Reading reports
    + ./coverage.txt bytes=447884
==> Appending adjustments
    http://docs.codecov.io/docs/fixing-reports
find: unrecognized: ./vendor/golang.org
BusyBox v1.26.2 (2017-06-11 06:38:32 GMT) multi-call binary.

Usage: find [-HL] [PATH]... [OPTIONS] [ACTIONS]
```

It finds no files to upload, so the reports are empty.

**Comment by stevepeak** [comment]
Thanks for reporting. This find error is during report fixes and is odd. I'll have to review it more.
Meanwhile try this:

```
bash <(curl -s https://codecov.io/bash) -X fixes
```

**Comment by kbakk** [comment]
I'm seeing this error as well, however it succeeded with the report upload. I'm on `node:12-alpine`, having used `apk add --no-cache git curl bash` to be able to run codecov-bash. Adding `findutils` fixed this for me.

**Comment by challgren** [comment]
I can confirm adding findutils fixes and resolves this issue.

**Comment by Maxwell2022** [comment]
Similar error on our end with another flag:

```
==> Running gcov in . (disable via -X gcov)
find: unrecognized: -execdir
BusyBox v1.31.1 () multi-call binary.
```

**Comment by thomasrockhu** [comment]
Hi @Maxwell2022, if this is still an issue, please open a ticket in our [community boards](https://community.codecov.io).
