### ISSUE TITLE
CircleCI: inconsistent args for build/job with codecov-python

### ISSUE THREAD

**Issue by blueyed** [codecov/codecov-bash#95]
https://github.com/codecov/codecov-bash/blob/7e6cfa3935aeb29de57298bda496dad27b24aa37/codecov#L541-L542

vs

https://github.com/codecov/codecov-python/blob/adc22c19f3e924cac15a7ee25edfb3a5b518bf7c/codecov/__init__.py#L345-L346

```python
build=os.getenv('CIRCLE_BUILD_NUM') + "." + os.getenv('CIRCLE_NODE_INDEX'),
job=os.getenv('CIRCLE_BUILD_NUM') + "." + os.getenv('CIRCLE_NODE_INDEX'),
```

**Comment by drazisil** [comment]
This may be a bug in the python uploader, or it is handled differently. The bash uploader correctly handles CircleCI build URLs.

**Comment by blueyed** [comment]
@drazisil 
Ok.  Can you move the issue there then?
(This issue just documents / points out that they differ - I cannot say which is correct, but they should be the same)
